### ISSUE TITLE
mint start modifies source.

### ISSUE THREAD

**Issue by Camto** [mint-lang/mint#10]
Running `mint start` changes the sources files to use two space indenting every time I save my files. This really confuses the text editors redo-undo feature, undoing makes Sublime text use half two space indenting and half tab indenting for whatever reason.

I think letting tabs be a thing would help "developer happiness" as something that is being focused on because for me, and other people using non two space indenting that automatic change can be a tad annoying.

**Comment by gdotdesign** [comment]
There are two planned features that will help with this:

1. Allow specifying the indent level or characters (2 spaces, 4 spaces, etc..) for the formatting
2. Add a flag to the `start` command to turn off automatic formatting

I don't have an ETA for this, but it probably won't be long.

**Comment by manveru** [comment]
Might be worth mentioning that we could possibly read an `.editorconfig` http://editorconfig.org/ file that automates this configuration.

**Comment by gdotdesign** [comment]
I think the `.editorconfig` is a good idea, anyone knows if there is  a shard that parses that format?

**Comment by kingsleyh** [comment]
this should be easy to port to Crystal - however it only goes up to 0.9 and the latest is 0.12 - not sure what the difference in functionality is - I think it would take me a few hours to port this - however I don't want to support it or update it to 0.12 - as too busy at the moment.

https://github.com/editorconfig/editorconfig-core-ruby

**Comment by gdotdesign** [comment]
The `indent-size` can now be set in the `mint.json` file in the `formatter-config` object (in 0.4.0)
