### ISSUE TITLE
Allow style to be defined in modules or find a solution to allow common code that uses styles

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#102]
I have some common html that I wanted to share with other components - and it seemed like a good idea to put it in a module that can be shared - unfortunately the html contains styles and currently you can't put styles in a module only a component.

one solution is to allow styles definitions in modules.

**Comment by gdotdesign** [comment]
Can you provide some exact use cases for this? 

The style restrictions come from the idea is that components are the unit of composition, what would be the downside of moving the common html to a component and using that?

Implementation wise it would not be that hard to allow styles in modules.

**Comment by kingsleyh** [comment]
ok - yes maybe it's better to just move it to a component.
