### ISSUE TITLE
RFC: Sum types and corresponding match syntax?

### ISSUE THREAD

**Issue by creatorrr** [mint-lang/mint#105]
Hey guys!

Many web APIs are polymorphic and their return types are different in different contexts. It can be difficult  to model them using `mint`'s existing built-in types. For example, the `navigator.clipboard.read()` API returns [`DataTransferItem`](https://html.spec.whatwg.org/multipage/dnd.html#datatransferitem) which can either be a `String` or a `File` depending on what's in the user's clipboard. 

At the moment, it's not straightforward how to write a mint counterpart for such APIs. Not sure how this would be done but happy to brainstorm and work on a PR if there's interest.

Possible solutions:

 - Adding a variadic built-in type e.g. `OneOf(String, File)` 
 - Sum (union) types support e.g. `String | File` and corresponding syntax for pattern matching etc. maybe something like [this](https://github.com/mint-lang/mint/issues/104).

Thoughts?

**Comment by gdotdesign** [comment]
I don't know if you are familiar with Algebraic Data Types from Elm https://www.elm-tutorial.org/en/01-foundations/05-union-types.html, but Mint has support for them using `enum` (which looks like it's not documented) for an example you can check out this https://github.com/mint-lang/mint-realworld/blob/master/source/Api.mint#L1 

For the `DataTransferItem` it could look something like this:
```
enum DataTransferItem {
  F(File)
  S(String)
}
```

and then match them like this: 
```
match (dataTransferItem) {
  F file => ...
  S string => ...
}
```

**Comment by gdotdesign** [comment]
Closing this issue because I think it's solved, feel free to open it again if you have any input.
