### ISSUE TITLE
mint build accidentally uses non relative path on Ubuntu.

### ISSUE THREAD

**Issue by Camto** [mint-lang/mint#11]
I used `mint build` and the generated HTML file doesn't work locally because it uses `<script src="/index.js"></script>` (correct: `<script src="./index.js"></script>`) which makes the computer think I want a file `index.js` from the top of the drive. I know `mint start` can work around that but it would be nice to be able to test out `mint build` locally.

**Comment by gdotdesign** [comment]
It's a two fold thing:
1. if deployed on a web server the URL needs to be absolute for the pages of an SPA to work. Usually every URL resolves the `index.html` which for an URL like this `/users/:id` would means that it needs to resolve the `index.js` from location that it reaches which is an absolute path.
2. If you want to test it locally or build a Chrome or Electron application then you would need relative path, but in this case reloading a page that's on a deeper path would automatically fail.

I'm not against a configuration option or a command line flag for which controls whether the URLs are absolute or relative.

**Comment by brycefisher** [comment]
@gdotdesign I'd love to have the option to make all paths relative via configuration option! Is that still on the table?

**Comment by gdotdesign** [comment]
It was implemented when this issue was closed: `mint build --relative` which makes all paths in the `index.html` relative.

**Comment by brycefisher** [comment]
Ah! Thank you so much.
