### ISSUE TITLE
CLI: Ability To Upgrade And Manage Mint Versions

### ISSUE THREAD

**Issue by s0kil** [mint-lang/mint#112]
Proposing an ability for the Mint installation to update itself, Example: `mint upgrade`.

It would also be productive to have an easy way to switch mint versions.
If `/usr/local/bin/` contains `mint-0.4.0`, `mint-0.3.1`, `mint-0.3.0`, etc, then we can link `/usr/local/bin/mint` to desired version: `mint use 0.2.1`, `mint use stable`, `mint use dev`, dev containing the latest daily binary release.

**Comment by s0kil** [comment]
API Proposal:
- `mint version` Returns currently selected Mint version
- `mint version 1.0.9` Set the Mint version, if version not found, confirm with user to proceed installation.

**Comment by gdotdesign** [comment]
I think we should add Mint to https://github.com/asdf-vm/asdf instead of implementing the same thing ourselves and promote that in the documentation.

**Comment by gdotdesign** [comment]
I've created a plugin for asdf here: https://github.com/mint-lang/asdf-mint
