### ISSUE TITLE
Mangle names only for final builds

### ISSUE THREAD

**Issue by TeddyDD** [mint-lang/mint#115]
Development server should not mangle names so it's easier to see Dom structure in browser's inspector

**Comment by gdotdesign** [comment]
Do you mean not mangle CSS classes and variables right?

**Comment by TeddyDD** [comment]
Yup, it would be great.  react-developer-tools are also helpful, It might be good idea to mention them in the docs for noobs like me :)

**Comment by gdotdesign** [comment]
I've been thinking about this and the problem with using non mangled classes in development is that you can target nested components with it like this:

```
component Nested {
  style base {
    color: green;
  }

  fun render : Html {
    <div::base>
      "World"
    </div>
  }
}

component Main {
  style base {
    color: red;

    & .nested-base {
      color: yellow;
    }
  }

  fun render : Html {
    <div::base>
      "Hello"
      <Nested/>
    </div>
  }
}
```

Which would result in a yellow `World` instead of green. I myself have run into this in my project.

I'm suggesting an other way of identifying elements using the `mint-development-class` attribute which would be added on development and removed in build. I think this is less abusable then using the `class`.

I'm open to other suggestions though :)

**Comment by s0kil** [comment]
What about just `{class}-mint` during development?
Long class names make it more difficult working in devtools.

**Comment by justchen1369** [comment]
Perhaps append a unique identifier after the element name?

**Comment by Danil-Lapirow** [comment]
> What about just `{class}-mint` during development?
> Long class names make it more difficult working in devtools.

Maybe just `{component}-{class}` because they are scoped?

**Comment by gdotdesign** [comment]
What I am proposing is that elements with styles attached to them would get it as attributes (`ui-toggle--base`) this would make them easier to spot in the dev tools:

Given there is this component:
```
component Ui.Toggle {
  ...
  
  style base {
    ...
  }

  style label {
    ....
  }

  style overlay {
    ...
  }

  ...

  fun render : Html {
    <button::base
      aria-checked={Bool.toString(checked)}
      disabled={disabled}
      onClick={toggle}
      role="checkbox">

      <div::label aria-hidden="true">
        <{ onLabel }>
      </div>

      <div::label aria-hidden="true">
        <{ offLabel }>
      </div>

      <div::overlay aria-hidden="true"/>

    </button>
  }
}
```

It would seen in the dev tools as: 
```
<button 
  ui-toggle--base
  style="variables..."
  aria-checked="true"
  disabled="false"
  class="a-a">

  <div 
    ui-toggle--label
    style="variables..." 
    aria-hidden="true"
    class="a-b">

    ON
  </div>

  <div 
    ui-toggle--label
    style="variables..." 
    aria-hidden="true"
    class="a-b">

    OFF
  </div>

  <div 
    ui-toggle--overlay
    style="variables..." 
    aria-hidden="true"
    class="a-c">
  </div>
</button>
```

As I stated earlier my concern is that if they are only there in development mode than they can be targeted and would break in release mode, so maybe we should add it to release mode as well with a flag (`--remove-style-identifiers`) that would remove it.

**Comment by Danil-Lapirow** [comment]
Why a-b?

**Comment by matthewmcgarvey** [comment]
In my work on [LuckyStyleable](https://github.com/matthewmcgarvey/lucky_styleable), I took from a Rails library called ViewComponent that is doing an [experiment with CSS encapsulation](https://github.com/github/view_component/tree/css-encapsulation).

We update the css classes/ids to follow this pattern: `{{class_name}}_{{first 6 characters of hexdigest}}_{{class/id}}`

The classname and hexdigest ensures the css doesn't bleed outside of the component but the name of the class is still there. The class name is always the same when re-rendering, but the hexdigest changes on recompiles and applies to all styles in the class.

If this was applied to Mint:

```mint
component Ui.Toggle {
  ...
  
  style base {
    ...
  }

  style label {
    ....
  }

  style overlay {
    ...
  }

  ...

  fun render : Html {
    <button::base
      aria-checked={Bool.toString(checked)}
      disabled={disabled}
      onClick={toggle}
      role="checkbox">

      <div::label aria-hidden="true">
        <{ onLabel }>
      </div>

      <div::label aria-hidden="true">
        <{ offLabel }>
      </div>

      <div::overlay aria-hidden="true"/>

    </button>
  }
}
```
Becomes

```html
<button 
  ui-toggle--base
  style="variables..."
  aria-checked="true"
  disabled="false"
  class="Toggle_ae123f_base">

  <div 
    ui-toggle--label
    style="variables..." 
    aria-hidden="true"
    class="Toggle_ae123f_label">

    ON
  </div>

  <div 
    ui-toggle--label
    style="variables..." 
    aria-hidden="true"
    class="Toggle_ae123f_label">

    OFF
  </div>

  <div 
    ui-toggle--overlay
    style="variables..." 
    aria-hidden="true"
    class="Toggle_ae123f_overlay">
  </div>
</button>
```

Still globally unique but a human can make the connection between the generated class and where the css came from.

**Comment by matthewmcgarvey** [comment]
I was looking into this a bit. To be able to do something like my last comment. The hex value has to be consistent for a component, at the very least, the css declaration has to match the class name usage. The problem I came across is that the process to create the css class names are only given the css style or the html style name https://github.com/mint-lang/mint/blob/155cb36971342476fec3ec9e79e28c4c94a96a0c/src/style_builder.cr#L195-L197

Somehow there needs to be a connection from the styles definition and usage to the component it is defined in. I tried passing down a hash id but it got crazy trying to figure out everything the id needed to be passed down into. It would be better if every node had a reference to it's parent so that we could traverse up the AST looking for the component and get the hash id from that.

Any thoughts?

**Comment by gdotdesign** [comment]
> It would be better if every node had a reference to it's parent so that we could traverse up the AST looking for the component and get the hash id from that.

We can add the reference to the component to the `style` node only, it wouldn't be that hard.

**Comment by gdotdesign** [comment]
An other possibility is to add the mapping to the type checker [`Artifacts`](https://github.com/mint-lang/mint/blob/master/src/type_checkers/artifacts.cr) at the type checking phase.

```
@componentStylesMap : Hash(Ast::Style | Ast::HtmlStyle, Ast::Component)
``` 

The artifact is used by the compiler too and could be passed to the `StyleBuilder` WDYT?
