### ISSUE TITLE
"dyld: Library not loaded" even after installing crystal

### ISSUE THREAD

**Issue by fuzzthink** [mint-lang/mint#117]
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib
  Referenced from: /usr/local/bin/mint
  Reason: image not found
Abort trap: 6

Even after crystal is installed.

Tried with nix, it tries to install the old v0.3.1 and it error-ed as well:

```
dev $ nix-env -f channel:nixpkgs-unstable -iA mint
unpacking 'https://nixos.org/channels/nixpkgs-unstable/nixexprs.tar.xz'...
installing 'mint-0.3.1'
error: Package ‘duktape-2.3.0’ in /nix/store/ac6m1dqlh9ixlanpiyysnvdahqw5zfwy-nixexprs.tar.xz/pkgs/development/interpreters/duktape/default.nix:25 is not supported on ‘x86_64-apple-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by fuzzthink** [comment]
First issue fixed with instructions added in https://github.com/mint-lang/mint-website/pull/15 .

If would be nice if `nix` install works and v0.5 is installed instead of older version.

**Comment by gdotdesign** [comment]
Thanks!

The `nix` package is maintained by @manveru and hasn't been updated to `0.5` yet.

**Comment by fuzzthink** [comment]
I see. You can close the ticket if you don't want to track the `nix` error/version here.

**Comment by manveru** [comment]
Hi @fuzzthink sorry, I wasn't actively using Mint, so I didn't notice the new version. I made a PR for 0.5.0 at https://github.com/NixOS/nixpkgs/pull/60410

**Comment by manveru** [comment]
Please note that I didn't test this on Darwin, I assume that the dependency on duktape still will prevent you from building it. I'm not sure why it's marked as linux only, but I suggest you try building it by setting the `allowUnsupportedSystem = true;` and update nixpkgs accordingly.

**Comment by gdotdesign** [comment]
Closing since the PR for the new version is merged.
