### ISSUE TITLE
How to import local file and use npm packages

### ISSUE THREAD

**Issue by fuzzthink** [mint-lang/mint#118]
Eg. Would dependencies be via manual edit of mint.json?  How does the dependency look like?

Can you provide a quick example on say using nodejs' `fs.readFile`?

**Comment by fuzzthink** [comment]
I see mint has `File` for file io. Maybe eg. of `fs.readDir`?

**Comment by fuzzthink** [comment]
Don't want to open too many issues, so changed the title. 

In general, how do I use install npm packages?

How do I import local mint files?

**Comment by fuzzthink** [comment]
Ah, found answer to local file in https://guide.mint-lang.com/reference/functions#calling-a-function

**Comment by gdotdesign** [comment]
Hey there, I'm a little confused of what is it that you want to do :) 

> Can you provide a quick example on say using nodejs' fs.readFile?

Mint is for building the front-end part of an application so it does not run on nodejs and there is no local file system access like in nodejs since all the code only runs in the browser.

> I see mint has File for file io. Maybe eg. of fs.readDir?

Yes `File` is for handling files you can see an example here: https://www.mint-lang.com/examples/file-handling

> In general, how do I use install npm packages?

Mint does not use npm packages, maybe in the future it might.

> How do I import local mint files?

You don't need to import anything, files in the `source-directories` are all loaded by default, anything in them is available in every other file.

**Comment by fuzzthink** [comment]
I see. To me, aside from its beta status, mint is the only language that checks the most important boxes I care about: simple, typed, FP (yes, only pipe forward pales in comparison vs. languages like F# and Reason, but it makes up for it in its simplicity).

So I was looking at it with the goal of using it as a js code generator. I see that doesn't look realistic since it builds a single index.js and can't use existing javascript packages.

I do think js interop should be given a top priority after 1.0. 

On a similar note, I see inlining js is done via backquotes. Should the tokens be changed to something else since backquotes are used in js?

**Comment by gdotdesign** [comment]
> So I was looking at it with the goal of using it as a js code generator.

At what capacity? The language is built around web applications, what parts of it would you use for code generation?

It is possible to make a subset of the language without components and routes and stores I just don't know what it would be like.

> On a similar note, I see inlining js is done via backquotes. Should the tokens be changed to something else since backquotes are used in js?

Backqoutes can be escaped just like the normal qoutes in a string https://github.com/mint-lang/mint/blob/7aa062369de2636cea475a7b24348d0a59cb895e/core/source/Test/Context.mint#L64

I don't know what else could work better.

**Comment by fuzzthink** [comment]
Thanks for the reply, closing.
