### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#120]
Fails to build with `mint build` but the reason why is not known:

```⚙ Ensuring dependencies... 1μs
⚙ Clearing the "dist" directory... 18μs
⚙ Copying public folder contents... 17.327ms
⚙ Compiling your application:
  ➔ Parsing 6 source files... Unhandled exception: Negative count: -276 (ArgumentError)
  from String#[]<Int32, Int32>:String
  from Mint::Message+@Mint::Message#render<Mint::Render::Terminal>:IO+
  from Mint::Cli::Build#parse_and_run:Nil
  from Mint::Cli#parse_and_run:Nil
  from main```

**Comment by kingsleyh** [comment]
The problem was due to missing double quotes in markup:

```
<div>"Some stuff "<strong>OOPS</strong>" and more stuff"</div>
```
fixed by "OOPS" but the error message did not help me to locate this error.

**Comment by gdotdesign** [comment]
I've run into this as well, but I cannot reproduce it from this example alone. 

Is there anything else you can tell me about it?
* what version are you running on? If it's not the `master`, can you check if it occurs there too?
* it would help to have see more of the code

Thanks.

**Comment by gdotdesign** [comment]
Also I've fixed a crash about `Negative Argument` here 050508df82a680a002cae333c930f60a2840c48f maybe it's the same.

**Comment by kingsleyh** [comment]
For my case at least - it seems to be fixed :)

**Comment by gdotdesign** [comment]
Great!
