### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by gdotdesign** [mint-lang/mint#122]
It's difficult to install Mint on macOS because of the dependencies and there is no static linking available, it would be great to have a Homebrew forumla for Mint.

Since I'm using Linux (and does not own a Mac), it's harder for me to do it, so I thought it would be a great issue for someone who wants to contribute.

I gathered some information which might be helpful:
* Crystal formula :arrow_right: https://formulae.brew.sh/formula/crystal
* Probably we need a bottle :arrow_right: https://docs.brew.sh/Bottles
* Forumla cookbook :arrow_right: https://docs.brew.sh/Formula-Cookbook
* Crystal formula source code ??? :arrow_right: https://github.com/crystal-lang/homebrew-crystal

Let me know here if you are interested working on this.

**Comment by Acciaiodigitale** [comment]
I'll try this w.e.

**Comment by Acciaiodigitale** [comment]
brew tap acciaiodigitale/homebrew-mint-lang
brew install mint-lang
mint-lang version

<img width="1439" alt="Schermata 2019-06-01 alle 12 13 15" src="https://user-images.githubusercontent.com/26814295/58747118-ca797980-8466-11e9-8f9c-357b280a127f.png">

**Comment by Acciaiodigitale** [comment]
After some test we can close the issue and integrate this instructions in the docs

**Comment by gdotdesign** [comment]
Thank you very much! :+1: 

I saw that `crystal` is a dependency, so the users need to install it first with `brew install crystal`? or is it installed as automatically? 

I'll try to test it out with people in the office today :slightly_smiling_face:

**Comment by Acciaiodigitale** [comment]
Sorry. I'm not so expert of Homebrew.
If you do
```
$ brew tap acciaiodigitale/homebrew-mint-lang
$ brew install mint-lang
```
Crystal will be installed automatically!

**Comment by gdotdesign** [comment]
Added the instructions to the website :+1: Thank you again! :smile:
