### ISSUE TITLE
--auto-format badly indent multiline strings

### ISSUE THREAD

**Issue by gaku-sei** [mint-lang/mint#129]
When using the `--auto-format` option with `mint start`, the multiline strings becomes a bit funky:

![Enregistrement de l’écran 2019-06-13 à 14 35 36](https://user-images.githubusercontent.com/3982371/59406373-e0812580-8de8-11e9-8973-952c73396a87.gif)

The indentation goes on the right endlessly.

**Comment by gdotdesign** [comment]
I'm aware of this issue, sadly it's hard to fix at this time because of how the formatter works.

If anyone can give it a shot to fix it, it would be helpful :pray:

**Comment by gdotdesign** [comment]
Fixed in #138
