### ISSUE TITLE
Required properties

### ISSUE THREAD

**Issue by gaku-sei** [mint-lang/mint#132]
Required properties would allow the component to leave the property uninitialized!

```
required property value : String /* No default */
```

This would probably lead to some error at compile time if the parent doesn't provide any values.

**Comment by gdotdesign** [comment]
This can be implement but I'm not sure it's necessary or not :slightly_smiling_face: 

I never needed to leave out the default value and besides it's nice documentation on what the actual value should be.

**Comment by gdotdesign** [comment]
Closing since I answered in the previous comment and no additional discussion took place.

Feel free to open it again if you would like to discuss it further.

**Comment by luncheon** [comment]
I think a compilation error indicating `the required property is not provided` can help us fix the code.

How do you think?

**Comment by gdotdesign** [comment]
I still don't feel that we need this feature.

:+1: if you would like to have required properties (without a default value) :-1: if you don't

**Comment by Namek** [comment]
@luncheon @gaku-sei can you provide us some cases?

**Comment by luncheon** [comment]
* url of a link or image
* label of a tab
* complex record property: providing default value is boring and using `Maybe` makes code dirty

**Comment by luncheon** [comment]
```
record User {
  id : String
  name : String
  email : String
  /* many properties */
}

component UserTable {
  property users : Array(User) = []

  fun render : Html {
    <table>
      for (user of users) {
        <UserRow user={user}/>
      }
    </table>
  }
}

component UserRow {
  property user : User /* required */
}
```

**Comment by gdotdesign** [comment]
@gaku-sei thanks for the use-cases the record one is one that I didn't think about.
