### ISSUE TITLE
Route parameters don't always coerce

### ISSUE THREAD

**Issue by ezrast** [mint-lang/mint#134]
Given a routes block like this and visiting `/0`:
```mint
routes {
  /:param (param : Number) {
    sequence {
      /* good */
      Debug.log(1 * param)      /* Number 0 */
      Debug.log(1 * param == 0) /* true */

      /* bad */
      Debug.log(param)      /* String "0" */
      Debug.log(param == 0) /* false */
    }
  }
}
```
The bottom two Debug.log lines incorrectly treat `param` as a String even though it's typed as a Number. This behavior can also occur outside of the `routes` block if you pass `param` to a function or save it in a store.

**Comment by gdotdesign** [comment]
Thank you for reporting! This is actually a missing the implementation, I will keep this issue open for that.
