### ISSUE TITLE
Embedding Mint

### ISSUE THREAD

**Issue by manveru** [mint-lang/mint#144]
I'd like to embed a mint component inside an existing webpage, but right now Mint is replacing the whole `<body>`.
I'd like to do something like this:

    mint build --output main.js

And then use it like this in my HTML:

```html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  <title>Main</title>
  <link rel="stylesheet" href="whatever-you-want.css">
  <script src="main.js"></script>
</head>

<body>
  <div id="mint"></div>
  <script>
    Mint.Program.init({
      node: document.getElementById('mint')
    });
  </script>
</body>
</html>
```

**Comment by gdotdesign** [comment]
It's now in `master`, the downside is that the routes will not work this way.

**Comment by gdotdesign** [comment]
Forgot to write the command `mint compile --output program.js` and the you can embed with `Mint.embed(document.querySelector("#root"))`

**Comment by manveru** [comment]
Sorry, I just saw this now, gonna try it ASAP :)

**Comment by manveru** [comment]
Alright, I had to massage the output a bit by appending `;export default Mint;`. But I think that might just be some webpack weirdness. Thanks a lot, will try using this a bit more :)
