### ISSUE TITLE
mint-0.7.0-osx show version 0.6.0

### ISSUE THREAD

**Issue by Acciaiodigitale** [mint-lang/mint#147]
Hi @gdotdesign.

When I'm updating mint for homebrew I noticed that 

`
mint-lang version
`

still show 0.6.0

**Comment by s0kil** [comment]
@gdotdesign Forgot to update `shard.yml` (:

**Comment by Acciaiodigitale** [comment]
I recompiled from source: now homebrew version show already the right version

**Comment by gdotdesign** [comment]
Yes I forgot to update, I just released 0.7.1 for the new Crystal version and I didn't forgot to bump the version this time :sweat_smile:
