### ISSUE TITLE
Probably not the right place, but www.mint-lang.com is down

### ISSUE THREAD

**Issue by beginrescueend** [mint-lang/mint#150]
It's probably not the right place to report this issue, but www.mint-lang.com is down.  I was wanting to check out Mint, but can only view github.

I get "This site can’t provide a secure connection www.mint-lang.com sent an invalid response. ERR_SSL_PROTOCOL_ERROR."

**Comment by gdotdesign** [comment]
Thanks for reporting, I was in the process of deploying a new website for Mint and had a problem with the SSL setup.

It should be fixed now :slightly_smiling_face: 

Feel free to reopen this issue if it happens again.

**Comment by beginrescueend** [comment]
Thanks!
