### ISSUE TITLE
Format skips test files

### ISSUE THREAD

**Issue by ravinggenius** [mint-lang/mint#158]
I love that this project formatting built-in! I'm using Mint `0.7.1` on macOS (installed today via brew), and the only files in my project are what I get with `mint-lang init <name>`.

As a test I completely out-dended both `source/Main.mint` and `tests/Main.mint`, then ran `mint-lang format`:

```
➤ mint-lang format **/*.mint
Mint - Formatting files
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Formatted: source/Main.mint
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All done in 1.367ms!
```

I also tried `mint-lang format source/** tests/**` and `mint-lang format {source,tests}/**`, but each only formatted `./source`.

I was only able to format `./tests` with `mint-lang format tests/**`, but I'd really prefer to format all Mint files in one go.

**Comment by s0kil** [comment]
@ravinggenius `mint format` will now format directories based on the `source-directories` and `test-directories` configuration set in the `mint.json` file.

REF: https://www.mint-lang.com/guide/getting-started/configuration
