### ISSUE TITLE
Document lifecycle methods (eg. componentDidMount)

### ISSUE THREAD

**Issue by SeedyROM** [mint-lang/mint#161]
Hey everybody working on Mint! I just wanted to say thank you for this project, I only found it this afternoon. But this is probably my favorite thing since sliced bread, so good I've already mostly forgotten about Elm. (I'm also a Crystal enthusiast so I'm super super excited to see a project like this utilize it!)

*Alright on to the issue...*

In my first initial hours playing around and following the guide / examples / docs, I noticed a lack of component lifecycle methods (coming from React, Vue, etc this seemed odd). I however dug into the source code and found a spec test that described them and then found [this](https://github.com/mint-lang/mint/blob/2ae6bc1e77830d687af5930905344d4e8b5344b4/src/compilers/component.cr#L116-L120).

These methods clearly exist for components and I feel like they should have a small section in the guide and be mentioned in the docs as well. There is one example that uses the router to call code on page load (from the blog), [which just seems wrong](https://www.mint-lang.com/blog/handling-http-requests).

I don't mind taking this task on personally and I am happy to contribute to this project!

**Comment by gdotdesign** [comment]
Hey :)

> Hey everybody working on Mint! I just wanted to say thank you for this project, I only found it this afternoon. But this is probably my favorite thing since sliced bread, so good I've already mostly forgotten about Elm. (I'm also a Crystal enthusiast so I'm super super excited to see a project like this utilize it!)

You just made my day with this :smile: 

About the issue, you are right, they are not documented which is probably on me :slightly_smiling_face: if you would like to help out you can create a page for this on the website (which would be appreciated): https://github.com/mint-lang/mint-website-rails

A little background on the life-cycle methods: Mint is using React under the hood so the life-cycle methods are the same, but only the three that you linked is checked at compile time and they don't take any parameters.

If you need any more information about the website or the life-cycle methods let me know :+1:

**Comment by gdotdesign** [comment]
It's documented here now https://www.mint-lang.com/guide/reference/components/lifecycle-functions
