### ISSUE TITLE
Plans to decouple the language from the framework?

### ISSUE THREAD

**Issue by CuddleBunny** [mint-lang/mint#162]
While I'll probably stick with TypeScript for the most part, I find this language pretty cute. Are there any plans to decouple the language from the frameworks behind it so that it may be used with other tech or are they too closely coupled?

**Comment by gdotdesign** [comment]
It is certainly possible to have different compile targets, even non JavaScript ones. I sadly don't have the time to explore these options.

In a more practical sense the steps need to be taken:
- write the compiler using the output of the parser and type-checker
- write the runtime https://github.com/mint-lang/mint-runtime
- write the standard library https://github.com/mint-lang/mint/tree/master/core/source

**Comment by CuddleBunny** [comment]
Great, I couldn't find these other pieces at first glance. Looks like it shouldn't be too hard!
