### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by fuzzthink** [mint-lang/mint#164]
Since https://github.com/mint-lang/mint-website is in Archive mode (why?), here may be the next best place to point out that:

Examples have compile errors:
https://www.mint-lang.com/examples/drag
https://www.mint-lang.com/examples/counter
https://www.mint-lang.com/try (same eg. code as counter seems like)

https://guide.mint-lang.com/ can't be reached. git-book issue per https://github.com/mint-lang/mint/issues/125 ?

**Comment by Sija** [comment]
@fuzzthink new website code can be found here => https://github.com/mint-lang/mint-website-rails

**Comment by fuzzthink** [comment]
Closing this & opened https://github.com/mint-lang/mint-website-rails/issues/11
