### ISSUE TITLE
Styling CSS at-rules

### ISSUE THREAD

**Issue by ZebTheWizard** [mint-lang/mint#166]
Unless I'm missing something, there does not seem to be a way to write CSS at-rules. For example, @keyframes, @font-face, etc.

```
style base {
  	@keyframes animate-stripes {
    	   0% {
     	      background-position: 0 0;
    	   }
    	   100% {
      	      background-position: 60px 0;
    	   }
  	}
 }
```

Here is the compiled style...
```
.a @keyframes animate-stripes 0% {
  background-position: 0 0;
}

.a @keyframes animate-stripes 100% {
  background-position: 60px 0;
}
```

**Comment by gdotdesign** [comment]
Yes you are right it's not possible at the moment but it's a planned feature.

In the mean time you can put these in the `head` HTML file specified in the `mint.json`
- https://www.mint-lang.com/guide/getting-started/configuration
- https://www.mint-lang.com/guide/recipies/using-third-party-css

**Comment by Danil-Lapirow** [comment]
@media works just fine

**Comment by gdotdesign** [comment]
What we won't support:
- `@document`
- `@namespace`
- `@import`
- `@charset`
- `@page`

What we will support:
- `@font-face`
- `@keyframes`
- `@supports`
