### ISSUE TITLE
Development server not working on WSL

### ISSUE THREAD

**Issue by Cyklan** [mint-lang/mint#167]
first off, I already read #54, but I still can't get it to work.

I'm using a freshly installed WSL (Debian) and followed the linux install process from the [Mint homepage](https://www.mint-lang.com/install).

This is what I'm currently stuck with.
![image](https://user-images.githubusercontent.com/37187056/73939978-dcab9180-48ea-11ea-85f9-7272e70a6f14.png)

Trying to reach the development server on `127.0.0.1:3000` is unsuccessful.

Any advise?

**Comment by gdotdesign** [comment]
I'm not sure what the issue can be, you can try to compile it from source or use the docker image.

I'll keep this issue open and try to reproduce it in a container or something.

**Comment by Cyklan** [comment]
Just compiled from source, same issue.

I'll have to try docker on another pc, that might take a few more hours.

**Comment by gdotdesign** [comment]
An other issue what it might be that you need to use a terminal with TTY https://www.andreafortuna.org/2018/04/23/wsltty-a-better-terminal-emulator-for-windows-subsystem-for-linux/

When I tried to run the binary in in docker it was the same issue and adding `tty` fixed it https://github.com/mint-lang/mint-docker/blob/master/docker-compose.yml#L5

**Comment by Cyklan** [comment]
Got it working using docker 👍

**Comment by Namek** [comment]
> An other issue what it might be that you need to use a terminal with TTY [andreafortuna.org/2018/04/23/wsltty-a-better-terminal-emulator-for-windows-subsystem-for-linux](https://www.andreafortuna.org/2018/04/23/wsltty-a-better-terminal-emulator-for-windows-subsystem-for-linux/)

Same issue. This did not help.

**Comment by Namek** [comment]
Alright, so my workaround for working with Mint on Windows is by using Docker.

Dockerfile:
```Dockerfile
FROM alpine:latest

RUN wget -O mint https://bintray.com/mint-lang/mint/download_file?file_path=mint-latest-linux
RUN chmod +x mint

EXPOSE 3000
WORKDIR /proj
ENTRYPOINT ["/mint"]
```

Usage:
```
# build docker mint image from the Dockerfile folder
docker build -t mint .

# init project called my_project in folder c:/dev/Projects, this will create a folder my_project
docker run --tty -v c:/dev/Projects:/proj mint init my_project

# `mint start` from the project above
docker run --tty -v c:/dev/Projects/my_project:/proj -p 3000:3000 --rm -ti mint start -h 0.0.0.0

# then open http://localhost:3000
```

**Comment by D1ceWard** [comment]
I have the same problem...
But after some investigation, i found that the code hang on ` TCPSocket.new(ip, port, 0.25, 0.25).close` in `src/utils/server.cr` line 16 [(link)](https://github.com/mint-lang/mint/blob/master/src/utils/server.cr#L16)

I also found that i can't make `TCPSocket` work on WSL (forever hang), i don't know why (not enough understanding) but i think it's a crystal-lang bug... so after more investigation (on crystal issue tracker) i found a similar issue (https://github.com/crystal-lang/crystal/issues/8382) with a possible temporarily solution.

Replacing `TCPSocket`
```
# src/utils/server.cr#L15
def port_open?(ip, port)
  TCPSocket.new(ip, port, 0.25, 0.25).close
  false
rescue
  true
end
```

With `Socket`
```
# src/utils/server.cr#L15
def port_open?(ip, port)
  client = Socket.tcp(Socket::Family::INET, true)
  client.connect(ip, port, 0.25)
  client.close
  false
rescue
  true
end
```

And after testing/rebuild it's seems to work fine !
But i don't understand why `TCPSocket` don't work on WSL while an alternative do work...

**Comment by Sija** [comment]
@D1ceWard WSL has its own issues, like https://github.com/microsoft/WSL/issues/1554 for instance :)

**Comment by gdotdesign** [comment]
@D1ceWard thanks for investigating :+1: 

I'll try the solution in Linux and if it works I see no reason why we could not use it :slightly_smiling_face:
