### ISSUE TITLE
Tests require Chrome

### ISSUE THREAD

**Issue by johanbrandhorst** [mint-lang/mint#168]
Hi!

I love the look of this project, and I'm excited to learn more about it. I was trying to run some tests locally and got the following error:

```
$ mint test
Mint - Running Tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ TEST RUNNER ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

I cannot find the executable of browser: chrome 

Are you sure it's installed properly? 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```

I don't have `chrome` installed, and I couldn't even get this to work by symlinking `/usr/bin/chromium` to `/usr/bin/chrome`. I also couldn't find a reference for how to configure it to use a different browser (say, Firefox?).

Is it possible to configure `mint` to use a different browser? Is it possible to use `chromium`?

**Comment by s0kil** [comment]
@gdotdesign Any ideas? We do use `chromium` in the test runner https://github.com/mint-lang/mint/blob/master/src/test_runner.cr#L114-L125

**Comment by johanbrandhorst** [comment]
Oh, thanks for that link. To add some more details about my system:
```
$ uname -a
Linux johan-x1 4.19.99-1-MANJARO #1 SMP Mon Jan 27 16:36:28 UTC 2020 x86_64 GNU/Linux
$ which chromium
/usr/bin/chromium
```

**Comment by s0kil** [comment]
@johanbrandhorst That error is before or after symlinking chromium to chrome?

**Comment by johanbrandhorst** [comment]
I get the same error both with and without the symlink

**Comment by s0kil** [comment]
Got it, thank you.
Seems like this is the problem, https://github.com/mint-lang/mint/blob/master/src/test_runner.cr#L232-L265

**Comment by johanbrandhorst** [comment]
It works if I run it with `--browser=firefox`!

```
$ mint test --browser=firefox
```.

Thanks!

**Comment by s0kil** [comment]
What about `mint test --browser=chromium`?

**Comment by johanbrandhorst** [comment]
Terribly sorry, I think I've been running an old version of `mint`. Didn't realise the AUR package was so out of date. It all works fine on `0.7.1`.

**Comment by johanbrandhorst** [comment]
```
$ mint test --browser=chromium
Mint - Running Tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ TEST RUNNER ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

I cannot run the tests in the given browser: chromium 

The available browsers are: 

  • chrome

  • firefox

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```
To answer your last question though.

**Comment by johanbrandhorst** [comment]
```
$ mint test --browser=chrome
Mint - Running Tests
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Ensuring dependencies... 73μs
⚙ Compiling tests... 15.663ms
⚙ Starting test server...
⚙ Starting browser...
⚙ Test server started on http://127.0.0.1:3001/
⚙ Running tests:
.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 tests
  ➔ 1 passed
  ➔ 0 failed
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
All done in 688.174ms!
```
Does work with `chromium` though.

**Comment by s0kil** [comment]
We should document the command (build, test, etc) flags in https://www.mint-lang.com/guide/getting-started/using-the-cli
