### ISSUE TITLE
Is there a way to define global constants?

### ISSUE THREAD

**Issue by MrCreeper1008** [mint-lang/mint#169]
Sorry if I'm missing anything, but I can't seem to figure out a way to define global constants. In JavaScript, I can define a constant in a file like:  
```javascript
export const theme = {
  primaryColor: '#123456',
};
```
or
```javascript
export const CATEGORIES = ['cat1', 'cat2', 'cat3'];
```
How do I achieve this in `mint`? Thank you!

**Comment by gdotdesign** [comment]
There is no way to define global constants at this time.

The closes is to define a store with a state

```
store Globals {
  state categories : Array(String) = ["cat1", "cat2", "cat3"]
}
```

which can be referenced later by connecting to it or by using `Globals.categories`

**Comment by MrCreeper1008** [comment]
Will this affect performance? That compiles to something way more complicated than simple variables.

**Comment by gdotdesign** [comment]
I don't think it affects the performance in any meaningful way, since it will be set on initialization and not touched after that, so it's little more then a variable lookup.

I'll try to figure something out for this soon :slightly_smiling_face:

**Comment by MrCreeper1008** [comment]
Thank you so much! Maybe something like: 
``` 
module MyConstant {
  constant CATEGORIES = ["cat1", "cat2", "cat3"]
}
``` 
?

**Comment by gdotdesign** [comment]
I was just thinking plain global constants, but it might makes more sense to have it in a module like you suggested.

**Comment by MrCreeper1008** [comment]
Top level global constants are useful too. Would be great if both are supported.

**Comment by gdotdesign** [comment]
I've started to work on it in this branch https://github.com/mint-lang/mint/tree/constants

So far I decided that `constant` will be available for **stores, components and modules**. They can be accessed by name inside the entities, can be connected to if they are in a store.

The only problem I ran into so far is that accessing the constants in a module from outside like this `Module.NAME` is ambiguous because it is a valid type name, so to access constants we need a new syntax which is `Module:NAME` at this point (I am open to a different syntax).

**Comment by Sija** [comment]
I'd go for `Module::NAME` - `::` is quite a popular choice in this regard.

**Comment by gdotdesign** [comment]
Sadly that would be ambiguous as well because of enums (`Maybe::Just`)

**Comment by MrCreeper1008** [comment]
Can the compiler tell between an enum and a module?

**Comment by gdotdesign** [comment]
@MrCreeper1008 since we don't have lexer (instead of tokens we go straight to AST) the parser is entity aware and both parses kind of the same until a point and we have no way to tell them apart.
