### ISSUE TITLE
Sharing component logic with mixin/react hook-like pattern?

### ISSUE THREAD

**Issue by MrCreeper1008** [mint-lang/mint#170]
Hopefully something like:
```
mixin SharedLogic {
  fun renderComponent : Html {
    <div><{ "test" }></div>
  }
}

component MyComponent with SharedLogic {
  fun render : Html {
    renderComponent()
  }
}
```

**Comment by gdotdesign** [comment]
It is certainly a feature that could be implemented, however I don't know if it's necessary. Can you show some examples where this would be useful?

In my product where the front-end is around ~12K loc I didn't needed this yet. Generics (#130) could potentially do the same thing, would that be enough?

**Comment by MrCreeper1008** [comment]
I don't think generics are the same thing.  

One example that comes to mind is listening to window size changes:  
```
mixin WindowSizeListener {
  fun componentDidMount() {
    window.addListener('i-forgot-the-event-name', onWindowSizeChanged)
  }

  fun componentWillUnmount() {
    window.removeListener('i-forgot-the-event-name', onWindowSizeChanged)
  }

  fun onWindowSizeChanged(event: Event)
}
component MyComponent with WindowSizeListener {
  override fun onWindowSizeChanged(event: Event) {
    // do stuff
  }
}

component MyAnotherComponent with WindowSizeListener {
  override fun onWindowSizeChanged(event: Event) {
    // do another stuff
  }
}
```
I just need to mixin `WindowSizeListener` with components that need to be aware of the window sizes, without writing the same logic again and again for each component.

**Comment by MrCreeper1008** [comment]
React does recommend hooks instead of mixins, so we should probably support hook pattern instead of mixins, but you get the idea.

**Comment by gdotdesign** [comment]
We already have a language feature to support this kind of pattern. You can define providers which you can use later, for example here is the provider for the window resize: https://github.com/mint-lang/mint/blob/master/core/source/Provider/Resize.mint

You can use it like this:
```
component Main {
  use Provider.Resize {
    resizes : handleResizes
  }

  fun handleResizes : Promise(Never, Void) {
    sequence {
      Debug.log("Window just has been resized!")
      next { }
    }
  }

  fun render : Html {
    <div>
    </div>
  }
}
```

This is not documented and I apologize for that, I'll try to work on the documentation more in the foreseeable future.

**Comment by MrCreeper1008** [comment]
Nah you're fine this is amazing. Thank you so much. I'll see what I can help with the documentation
