### ISSUE TITLE
Error when trying to `mint install` on https://github.com/mint-lang/mint-website

### ISSUE THREAD

**Issue by imorph** [mint-lang/mint#172]
Hi! 

I am getting error when trying to install dependencies:

```
Mint - Installing dependencies
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Constructing dependency tree...
  ✔ Updated mint-codemirror(https://github.com/mint-lang/mint-codemirror.git)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

░ INSTALL ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

I could not parse the mint.json for the package:
mint-codemirror(https://github.com/mint-lang/mint-codemirror.git) for the
version or tag: 6.1.0

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
There was an error exiting...
```

i just cloned github.com/mint-lang/mint-website and made `mint install`

mint version: Mint 0.7.1
platform: linux

**Comment by gdotdesign** [comment]
I'm sorry about this, the install page point to the build from the master branch and it contains some breaking changes like this.

It should work with the proper release of 0.7.1 :arrow_right: https://github.com/mint-lang/mint/releases/tag/0.7.1

**Comment by imorph** [comment]
@gdotdesign, thanks! With `mint` binary from 0.7.1 tag its working.
