### ISSUE TITLE
Feature Request: destructure first array element

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#177]
In functional languages we usually destructure a list for convenient recursive traversal of some tree/graph data.

For simplicity of an example let's just parse a flat array:

```
state someList = [1, 2, 3, 141424]

fun sumNumbers(elements : Array(Number)) : Number {
  traverse(0, elements)
} where {
  traverse = (acc : Number, els : Array(Number)) : Number {
    case (els) {
      [] => acc
      first::rest => traverse(first + acc, rest)
    }
  }
}
```

The important part is:

```
case (els) {
  [] => acc
  first::rest => traverse(first + acc, rest)
}
```

where `els` is destructured to the `first` element and the `rest` of the elements.

# Why?

In the above example we could use a simple `Array.map()` call or `for` syntax. However, coding anything like breadth/deep first search algorithms would benefit from a simpler syntax.

Currently, I am not aware of a simple way to split a list to first/rest parts in a one call.

**Comment by gdotdesign** [comment]
I think it is a good idea, I just need to think about how to implement it.

**Comment by s0kil** [comment]
What about this?
```
case (els) {
  [] => acc
  [head | tail] => traverse(head + acc, tail)
}
```

**Comment by Namek** [comment]
Looks like `Array(Array(Number))`. Or it would be `[[head | tail]]` then.

**Comment by s0kil** [comment]
`head` is the first element in the array, tail is the rest of the elements.

**Comment by gdotdesign** [comment]
I've gathered some patter matching / destructuring examples from different languages for lists / arrays:

Elm

```elm
listDescription : List String -> String
listDescription list =
 case list of
    [] -> "Nothing here !"
    [_] -> "This list has one element"
    [a,b] -> "Wow we have 2 elements: " ++ a ++ " and " ++ b
    a::b::_ -> "A huge list !, The first 2 are: " ++ a ++ " and " ++ b
```

Reason

```reason
switch (myArray) {
| [|1, 2|] => print_endline("This is an array with item 1 and 2")
| [||] => print_endline("This array has no element")
| _ => print_endline("This is an array")
};
```

F#

```
match list with
 | head :: tail -> head + sum tail
 | [] -> 0
```

Haskell

```haskell
take  0     _           =  []
take  _     []          =  []
take  n     (x:xs)      =  x : take (n-1) xs
```

Elixir

```elixir
[head | tail] = [1, 2, 3]
```
JavaScript

```
[a, b, ...rest] = [10, 20, 30, 40, 50];
```

-----------------
My proposal is below, and the reasoning is that it would be more familiar for people coming from JavaScript.

```
case ([]) {
  [] => ""                /* Empty array  */
  ["a"] => ""             /* Array with only one element */
  [a] => ""               /* Array with ony one element */
  [a, b] => ""            /* Array with ony two elements  */
  [a, ...middle, b] => "" /* Array at least with three elements */
  [...head, tail] => ""   /* Array at least two elements */
  [head, ...tail] => ""   /* Array at least two elements */
  [...items] => ""        /* Items would be the array */
  => ""                   /* Fallback as usual */
}
```
Any `case` with an array would be exhausted (no need for the fallback) if it would have a spread operator in it. 

I would need to think about which branches should raise an error depending the other branches.

**Comment by s0kil** [comment]
I don't see the point of `...`, it's simply unnecessary.
```
case ([]) {
  [head, middle, tail] => "" /* first, rest, last */
  [head, _,  tail] => ""        /* first, last */
  [head, tail] => ""             /* first, rest */
  => ""                              /* Fallback as usual */
}
```

**Comment by gdotdesign** [comment]
The `...` is required because without it this `[head, middle, tail]` is ambiguous, does it match only one element or multiple? if it matches multiple why it looks like `head` and `tail`?

**Comment by gdotdesign** [comment]
I'm fine with the way Elm does it, and using a pipe '|' does not fit into an array for me.

**Comment by Namek** [comment]
With Elm syntax you can't have `[a, ...middle, b]` nor `[...firsts, last]`, can you? However those probably complicate things internally. I'm after either this proposal or Elm syntax.

**Comment by Sija** [comment]
JS is the language that people will know more about, then any of the other mentioned here, so I'd go for `...` syntax.
