### ISSUE TITLE
Module String Additions

### ISSUE THREAD

**Issue by s0kil** [mint-lang/mint#178]
Functions to add into the standard lib String:
`String.toList : String -> List Char`
and potentially
`String.fromList : List Char -> String`

**Comment by gdotdesign** [comment]
:+1: let's make them `String.toArray` and `String.fromArray` because we don't have `List` at this point.

**Comment by Danil-Lapirow** [comment]
We can use String.join instead of String.fromArray

> 👍 let's make them `String.toArray` and `String.fromArray` because we don't have `List` at this point.

**Comment by s0kil** [comment]
@Danil-Lapirow https://www.mint-lang.com/api/modules/String#join

**Comment by Namek** [comment]
Maybe `fromChars` and `toChars`?

**Comment by s0kil** [comment]
@Namek
fromChars: String from an array of Chars?
toChars: String to array of Chars?

**Comment by s0kil** [comment]
We already have `String.split` and `String.join`, most functions mentioned seem unnecessary.

**Comment by Namek** [comment]
@s0kil should this issue still be open?

**Comment by gdotdesign** [comment]
Those functions does not have the same type signature (they take the separator) so I think we can add these for explicitness sake.
