### ISSUE TITLE
Array access

### ISSUE THREAD

**Issue by gdotdesign** [mint-lang/mint#18]
A syntax element is needed to do array access which uses the same brackets as the array literal `[]` but instead of returning an array it would return the corresponding element in the array.

```
fun item : Maybe(Number) {
  [1, 1, 2, 3][0] 
}

fun item : Maybe(Number) {
  array[0] 
} where {
  array = [1, 1, 2, 3]
}
```

- it can only have one **number literal** as the index
- should work on any expression (probably a new branch here: https://github.com/mint-lang/mint/blob/master/src/parsers/expression.cr#L11)
- type checking needs to be implemented on the expression which should raise an error if it does not evaluate to an array `Array(a)`
- the resulting type should be `Maybe(a)` where `a` is explicitly set from the result of the expression
- the JS implementation should be part of the runtime (https://github.com/mint-lang/mint-runtime) (with tests) which is called in the compiled script (`_at(array, index)`)
- **[EXTRA]** if the expression can be traced back to an array literal then the compiler should check if there is an item at the given index and raise an error if there isn't one

_If you start working on this issue please assign yourself to it._

**Comment by gdotdesign** [comment]
I've added you as a contributor :smile:

**Comment by manveru** [comment]
Thanks man :+1:

**Comment by manveru** [comment]
Sorry, I won't be having any time this week to work much on this anymore.
