### ISSUE TITLE
Ways to debug an app

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#184]
## Stores

We need access to state. I wish for at least a global variable that would contain all stores, so I could inspect it using browser DevTools.

Global variables are not the best idea for production apps though.

## Source maps

I just had a runtime error (no SSCCE, sorry) and had a really hard time debugging the minified code. Besides, everyone needs debugging. Even if it's no source mapping but just JavaScript code. Somewhat issued already here: https://github.com/mint-lang/mint/issues/115

**Comment by Namek** [comment]
@gdotdesign  label `feature-request`?

**Comment by gdotdesign** [comment]
Yep, part of this should be a dev tools story, the other is compiler / core lib.

**Comment by gdotdesign** [comment]
Closed with #702
