### ISSUE TITLE
Lack of unary minus operator

### ISSUE THREAD

**Issue by Namek** [mint-lang/mint#192]
In Elm I had a code:

```elm
case count of
    1 ->
        [ 0.0 ]

    2 ->
        [ -m / 2, m / 2 ]

    3 ->
        [ -m, 0.0, m ]

    4 ->
        [ -(m * 3 / 2), -m / 2, m / 2, m * 1.5 ]

    _ ->
        []
```

With Mint I had to use negative numbers instead of unary minus operator:

```
case (count) {
  1 => [0]

  2 =>
    [
      m / -2,
      m / 2
    ]

  3 => [m * -1]

  4 => [-1 * (m * 3 / 2)]

  => []
}
```

**Comment by gdotdesign** [comment]
I see no reason why this could not be implemented, and I suspect it would not be that hard to do.

If someone wants to give it a go, [`NegatedExpression`](https://github.com/mint-lang/mint/blob/master/src/parsers/negated_expression.cr) is similar implemetation wise.
