### ISSUE TITLE
Crystal 0.33.0

### ISSUE THREAD

**Issue by SeekingMeaning** [mint-lang/mint#196]
Just a heads-up that 0.33.0 was released a few days ago and introduces some breaking changes (e.g. `Time.now` -> `Time.local`)

**Comment by gdotdesign** [comment]
I've already upgraded to 0.33.0 and `master` is updated with the changes.

**Comment by Namek** [comment]
Shouldn't this be closed then?

**Comment by gdotdesign** [comment]
Yeah.
