### ISSUE TITLE
Environment access ( .env )

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#214]
Do we have a way of reading loaded environment file ?

The concept of this language sounds great by the way !

**Comment by gdotdesign** [comment]
> The concept of this language sounds great by the way !

Thanks :+1: :slightly_smiling_face: 

> Do we have a way of reading loaded environment file ?

I don't understand the question, you can access the loaded variables using this syntax `@VARIABLE`, you can find more information here :arrow_right: https://www.mint-lang.com/guide/reference/environment-variables

**Comment by Eternahl** [comment]
Perfect, that's what i was looking for !
I just missed it 😅 
Thanks
