### ISSUE TITLE
Embedding multiple apps in one page cause CSS conflicts

### ISSUE THREAD

**Issue by manveru** [mint-lang/mint#219]
If you import the JS for two different apps and they both define styles, the names of the styles will cause a merge, since it's just `a`, `b`, `c`, ...

It would be nice to be able to define a custom prefix to avoid collisions.

**Comment by JSMonk** [comment]
@gdotdesign, seems like it's already fixed by adding app-name as a CSS-prefix.

**Comment by gdotdesign** [comment]
Yes it is :tada: :smile: closing!
