### ISSUE TITLE
[Feature Request] Add the Mint language to GitHub's linguist

### ISSUE THREAD

**Issue by saadq** [mint-lang/mint#220]
I think it would be cool to add support for GitHub syntax highlighting/language statistics for Mint repositories. 

[Linguist](https://github.com/github/linguist) has [a guide in its CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) file for how to add a language.

**Comment by gdotdesign** [comment]
I agree that it would be cool however I don't think we are there yet:

> In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.

**Comment by gdotdesign** [comment]
I think we are starting to get where it's justified to do this :slightly_smiling_face: 

I would welcome anyone who would like to give this a go.

**Comment by bbugh** [comment]
I have created a branch for this: https://github.com/github/linguist/compare/master...bbugh:mint-lang?expand=1

I have a couple of points I need feedback on from @gdotdesign :

- the only generated `tmLanguage` I could find was in the `mint-vscode` repo. Would you rather create a separate repo for the grammars (which some languages do), or is it ok to point at this repo? Or something else?
- I used the green #02b046 from the web site active nav links for the "official" color, as I couldn't find any single color elsewhere that appeared to represent the language. Let me know if you would prefer a different color.
- For official samples, I selected items from the home page and from the `mint-realworld` repository. If you think there are better ones, I can change them.

**Comment by bbugh** [comment]
I created a draft PR on linguist, pending your official sing off https://github.com/github/linguist/pull/5402

**Comment by gdotdesign** [comment]
> the only generated `tmLanguage` I could find was in the `mint-vscode` repo. Would you rather create a separate repo for the grammars (which some languages do), or is it ok to point at this repo? Or something else?

At this point I think it's OK, can it be changed in the future?

> I used the green #02b046 from the web site active nav links for the "official" color, as I couldn't find any single color elsewhere that appeared to represent the language. Let me know if you would prefer a different color.

I think that's fine.

> For official samples, I selected items from the home page and from the mint-realworld repository. If you think there are better ones, I can change them.

That's fine too :slightly_smiling_face: 

-------------

I'm officially singing off :smile:

**Comment by bbugh** [comment]
I believe the grammar location can be freely changed in the future. I will go ahead with the PR!

**Comment by bbugh** [comment]
This is pending popularity on linguist, need more repos!

**Comment by Sija** [comment]
ftr, we're only **26** repo shy of the **200** [minimum](https://github.com/github/linguist/blob/16c70aef8cd62ca071231a380c69050f5e83c900/CONTRIBUTING.md#adding-a-language).

**Comment by frnco** [comment]
> ftr, we're only **26** repo shy of the **200** [minimum](https://github.com/github/linguist/blob/16c70aef8cd62ca071231a380c69050f5e83c900/CONTRIBUTING.md#adding-a-language).

Being unable to check the number of repos is a pain... Seriously disappointed by Github yet again, pretty embarrassing to have requirements that can't be checked by the people trying to meet them...

**Comment by Sija** [comment]
@frnco You could try pinging in the linked issue ppl responsible, perhaps 2nd voice would get 'em a bit motivated...

**Comment by Sija** [comment]
It finally had happened! 🎉 Thanks to the everyone involved! 🙏❤️🚀

**Comment by Sija** [comment]
Aaaand, it's live! 🌿 (example from [mint-realworld](https://github.com/mint-lang/mint-realworld))

> <img width="334" alt="image" src="https://user-images.githubusercontent.com/988/155204058-02201673-c768-4668-8d27-c1f08bbe6fe7.png">
