### ISSUE TITLE
Avoiding unknown CSS property error

### ISSUE THREAD

**Issue by luncheon** [mint-lang/mint#221]
```
There is no CSS property with the name: touch-action
```

I think it is too hard to support all CSS properties.  
Is there a way to avoid the error? If not, is there a plan to provide it?

I considered two ways:

1. syntax to avoid checking CSS properties
2. config to add allowed CSS properties

and I think 2 is safer.

**Comment by s0kil** [comment]
We should support all CSS properties and values that browser engines support.
## Chromium:
- [Primitive Values](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/css_primitive_value_units.json5)
- [Properties](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/css_properties.json5)
- [Values](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/css_value_keywords.json5)
- [Media Types](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/media_type_names.json5)
- [Media Features](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/media_feature_names.json5)
- [SVG Values](https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/css/svg_css_value_keywords.json5)

**Comment by s0kil** [comment]
@luncheon Please re-open issue, I'm saying we should support all CSS property/values that browser engines support, but we currently do not.

Example, [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) is a valid property, but it's not [defined in Mint](https://github.com/mint-lang/mint/blob/master/src/assets/css_properties)

**Comment by s0kil** [comment]
@gdotdesign Should we also define properties with a prefix such as `-webkit-`?
Otherwise, we could figure out that `transform` could also be `-webkit-transform`.

**Comment by s0kil** [comment]
@gdotdesign In the mentioned "properties-db.js" file, it also defines the available values for a property, we could use that to check the values?

**Comment by gdotdesign** [comment]
that is something I want to do and that file seems to be prefect for it :slightly_smiling_face: it's just not a priority right now so if you want to tackle it it would be awesome :smile:
