### ISSUE TITLE
How to use websockets?

### ISSUE THREAD

**Issue by ruslankonev** [mint-lang/mint#223]
It is possible?

**Comment by s0kil** [comment]
@ruslankonev Here is a good starting point: https://gist.github.com/gdotdesign/bc0117e17b984c09097a643092a18aac

**Comment by gdotdesign** [comment]
Also the same is here https://sandbox.mint-lang.com/sandboxes/N0iQTG1fduXoRA

**Comment by ruslankonev** [comment]
@gdotdesign, link was broken
