### ISSUE TITLE
Array destucturing conflicting with array access

### ISSUE THREAD

**Issue by gdotdesign** [mint-lang/mint#241]
Created from #225 

--------------

In the following snippet the syntax of array access and the next case branch is ambiguous:
```
case (arr) {
  [] => try { "lol0" }

  [head, ...tail] =>
    try {
      "lol1"
    }
}
```
I'm not sure how to resolve that, these are the options I see at the moment:

- making each case branch to require brackets `{}` (making them blocks)
- changing array access parsing so it would skip instead of raising an error on `]`
- branching the expression parsing not to parse array access as a top level expression in a branch

Anyone have other ideas?

**Comment by Namek** [comment]
I don't see how this is ambiguous, at least from a user perspective. There is a newline (even two) after the first `try` block.

I would welcome optional brackets for the `case` blocks, though.

**Comment by gdotdesign** [comment]
At this point it is valid to write this:

```
case (arr) { [] => "lol" [head, ...tail] => "lol1" }
```

I suppose we can make it that new lines required between branches.

Please vote :+1: for requiring new line :-1: for requiring brackets

**Comment by gdotdesign** [comment]
As it turns out this was actually a bug where the white space got consumed before the next branch.

A new line is not necessary any white space will do.
