### ISSUE TITLE
Feature Request: Emit compilation error message to the CLI for `mint start`

### ISSUE THREAD

**Issue by luncheon** [mint-lang/mint#243]
to jump to the file/line in the IDE.

**Comment by gdotdesign** [comment]
This feature will be supported by the language server #203

**Comment by luncheon** [comment]
@gdotdesign  
I'm sorry for my lack of clarity. I'd like to talk about "Jump to Error", not "Jump to Definition".

Some IDEs treat `(file path):(line number):(column number)` on the terminal as a link. Compilation error messages with error locations can be used for navigation.

Following is an example of TypeScript on VSCode.

![rkaav-e1yqw](https://user-images.githubusercontent.com/7709610/78880943-15095080-7a91-11ea-8604-8eeeb4dd51f5.gif)

**Comment by gdotdesign** [comment]
Oh I see :smile: 

So basically it's just `path/to/file:line:column` ? if so we can add that to every snippet which is displayed.

**Comment by luncheon** [comment]
I think the format `path/to/file:line:column` (or `path/to/file:line` without `column`) is used in general.

* `path/to/file:line:column`  
  TypeScript, GCC, GHC

* `path/to/file:line`  
  Java, Scala, Ruby

* `path/to/file(line,column)`  
  C#

* `path/to/file(line)`  
  D

Parentheses can be used for file names, so I think colon-separated is better.
