### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by TudorHulban** [mint-lang/mint#244]
Hi!
Just starting up, complete novice. Please consider adding in site documentation a change of directory in section install dependencies.
It is not clear if I should `cd` especially when tired...
Thank you

**Comment by gdotdesign** [comment]
Thanks :+1: will do!

**Comment by TudorHulban** [comment]
Bothering again. 
assets/head.html in using 3rd party CSS.
Maybe the head.html could reside in a pre created folder (`mint init`) in the initial structure. Easier to manage. 
I believe many of us would load the CSS references with the project as code file. 

Documentation hint:
This file could contain references to more than one CSS lib.

Thank you
