### ISSUE TITLE
Nav Bar error

### ISSUE THREAD

**Issue by TudorHulban** [mint-lang/mint#245]
Hi!
Trying to add a nav bar as per https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_navigation_bar .
Starting with:
```
component Main {
  fun render : Html {
    <div class="w3-bar w3-black">
      <a href="#" class="w3-bar-item w3-button"> xxx </a>
    </div>
  }
}
```
I get error:
```
I was looking for the closing tag but found xxx instead.
```
Any ideas?
Thank you

**Comment by gdotdesign** [comment]
In Mint you need quote the text you want to display (as a String basically):

```
 <a href="#" class="w3-bar-item w3-button"> "xxx" </a>
```

Its because in HTML white space is kind of weird and like this we have more control over them.

**Comment by TudorHulban** [comment]
Understood.
If I missed the quote text from documentation sorry, if not would suggest adding it to the site.
Thank you
