### ISSUE TITLE
RFC: RegExp Literals

### ISSUE THREAD

**Issue by luncheon** [mint-lang/mint#250]
I'd like to use regular expression literals with a syntax similar to JavaScript.

```
/^a/i
|> matches("ABC")
```

What do you think?

**Comment by gdotdesign** [comment]
I agree it would be useful, I'll keep this in mind for the roadmap.

**Comment by lukepighetti** [comment]
Which RegEx format do we want to use?

**Comment by gdotdesign** [comment]
We should start with JavaScript because that's where we compile to and see what can be done after that.
