### ISSUE TITLE
Not enough context in required props error

### ISSUE THREAD

**Issue by zephraph** [mint-lang/mint#252]
I got this error while working on my site:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3087225/80285419-c5fb2680-86f2-11ea-8531-3ed71840b372.png">

There's a component somewhere that isn't getting a required prop passed to it. But there's no indication of _where_ that is or what component.

**Comment by s0kil** [comment]
As you said, the error message should include additional details.

Here is an example where this error is thrown:
```
component Button {
  property name : String

  fun render : Html {
    <div>
      <{ name }>
    </div>
  }
}

component Main {
  fun render {
    <div>
      <Button/>
    </div>
  }
}
```
`name` is a required property, but was not specified for the `Button` component.
