### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by michaeldesu** [mint-lang/mint#26]
Support for foreign character rendering is needed - currently these are rendered as garbage characters

```
component Main {
  style base {
    font-family: sans;
    font-weight: bold;
    font-size: 50px;

    justify-content: center;
    align-items: center;
    display: flex;
    height: 100vh;
    width: 100vw;
  }

  fun render : Html {
    <div::base>
      <{ "こんにちは" }>
    </div>
  }
}
```

**Comment by manveru** [comment]
The problem is a missing `<meta charset="utf-8">` in the head tag of the default HTML. So maybe you can make a PR for https://github.com/mint-lang/mint/blob/master/src/utils/index_html.cr#L32 and add this tag?

**Comment by manveru** [comment]
![Looks like this atm, see that it's using a windows codepage encoding](https://user-images.githubusercontent.com/3507/40977838-5d8ee644-68d2-11e8-9da3-cdf21da6268b.png)

**Comment by gdotdesign** [comment]
The charset meta can be set from the `mint.json` file: https://github.com/mint-lang/mint/blob/master/src/utils/index_html.cr#L35

Example here: https://github.com/mint-lang/mint-website/blob/master/mint.json#L9

Maybe it should be `utf-8` if not specified otherwise, WDYT?

**Comment by manveru** [comment]
That would definitely be a safer default than not setting it at all.
