### ISSUE TITLE
Float values formatting regression

### ISSUE THREAD

**Issue by Sija** [mint-lang/mint#263]
After #259 float values started to loose `.0` part after formatting, running `make test-core` results now in:

```diff
diff --git a/core/tests/tests/Math.mint b/core/tests/tests/Math.mint
index debbd9a..cbbf6d0 100644
--- a/core/tests/tests/Math.mint
+++ b/core/tests/tests/Math.mint
@@ -92,7 +92,7 @@ suite "Math.random" {
       n =
         Math.random()

-      n >= 0.0 && n < 1.0
+      n >= 0 && n < 1
     }
   }
 }
```

/cc @s0kil

**Comment by s0kil** [comment]
Is this a big deal? `0.000000000000000` is simply `0`
If the float values are `n >= 0.1 && n < 1.1` they would not be modified.

**Comment by Sija** [comment]
Since in JS both, `0` and `0.0` are of the same type of `number` I guess it's fine to have it shortened up like this... 🤷‍♂️

**Comment by gdotdesign** [comment]
I'm not sure that we need to convert the numbers that we parse, is it even necessary? we don't do anything with that information.

**Comment by s0kil** [comment]
@gdotdesign Does that also mean we stop the formatter from transforming `10.120` into `10.12`?

**Comment by gdotdesign** [comment]
Yes, when formatting we just output what we parsed.
