### ISSUE TITLE
Allow extending modules with functions and constants.

### ISSUE THREAD

**Issue by s0kil** [mint-lang/mint#265]
Example:
```mint
module Array {
  fun test(array : Array(a)) {
    Array.size(array)
  }
}
```

Error Thrown:
```
The entity size you tried to reference does not exists in the module or store Array
```
The error should clarify that a core module  namespace was overwritten.

**Comment by s0kil** [comment]
#### Could We Support Extending A Module Under The Same Namespace?
```mint
extend module Array {
  fun test(array : Array(a)) {
    Array.size(array)
  }
}
```
or
```mint
module extends Array {
  fun test(array : Array(a)) {
    Array.size(array)
  }
}
```

**Comment by gdotdesign** [comment]
I've thought about open modules (like Ruby and Crystal does): on the one hand it's great that you can extend modules like that, on the other I think it will lead to people wanting to override functions defined in those modules.

Implementation wise It should not be a big issue, so it boils down to if people are fine with only additions to a module.

**Comment by s0kil** [comment]
Extendable modules, with immutable functions, sounds good.
