### ISSUE TITLE
Cannot use Enum's as a key for Map

### ISSUE THREAD

**Issue by jansul** [mint-lang/mint#268]
Hey, 

Not sure if I'm just using it wrong, but it looks like you cannot use enum members as keys in a Map.

Here's an example of this in action:
https://sandbox.mint-lang.com/sandboxes/YztcefM7LQvBSA
```
enum TestEnum {
  Field1
  Field2
  Field3
  Field4
}
component Main {
  property map : Map(TestEnum, String) =
    Map.empty()
    |> Map.set(TestEnum::Field1, "Value 1")
    |> Map.set(TestEnum::Field2, "Value 2")
    |> Map.set(TestEnum::Field3, "Value 3")

  fun getMapValue (test : TestEnum) : String {
    Debug.log(map)
    |> Map.get(test)
    |> Maybe.withDefault("Unknown")
  }

  fun render : Html {
    <div>
      <{ getMapValue(TestEnum::Field1) }>
      <{ getMapValue(TestEnum::Field2) }>
      <{ getMapValue(TestEnum::Field3) }>
      <{ getMapValue(TestEnum::Field4) }>
    </div>
  }
}
```
This should print "Value 1Value 2..." etc but instead prints "Unknown" 4 times.

**Comment by s0kil** [comment]
@jansul Could you give some details on what you are trying to achieve?
I do not think we expected enumerations to be used this way.

Here is how they are usually being used:
```mint
enum TestEnum {
  Field1
  Field2
  Field3
  Field4
}

component Main {
  fun getValue (test : TestEnum) : String {
    case (test) {
      TestEnum::Field1 => "Value 1"
      TestEnum::Field2 => "Value 2"
      TestEnum::Field3 => "Value 3"
      TestEnum::Field4 => "Value 4"
    }
  }

  fun render : Html {
    <div>
      <{ getValue(TestEnum::Field1) }>
      <{ getValue(TestEnum::Field2) }>
      <{ getValue(TestEnum::Field3) }>
      <{ getValue(TestEnum::Field4) }>
    </div>
  }
}
```

**Comment by jansul** [comment]
I've been trying to figure out the best way to structure forms in Mint. (I have no idea what I'm doing so please forgive me 😅)

One of the ideas I had was to store form values in a map and have generic get/set methods to access them. (I have a lot of fields so I didn't want to write a store method for each one)

Here's how that might look:
```
enum FormField {
  Field1
  Field2
  Field3
  Field4
}

store Form {
  state values : Map(FormField, String) = Map.empty()

  fun getFormValue (field : FormField) {
    values
    |> Map.get(field)
    |> Maybe.withDefault("")
  }

  fun setFormValue (field : FormField, value : String) {
    next { values = values |> Map.set(field, value) }
  }
}

component Main {
  connect Form exposing { getFormValue, setFormValue }

  fun handleOnChange (field : FormField, event : Html.Event) {
    Dom.getValue(event.target)
    |> setFormValue(field)
  }

  fun render : Html {
    <div>
      <input
        value={getFormValue(FormField::Field1)}
        onChange={handleOnChange(FormField::Field1)}/>

      <{ getFormValue(FormField::Field1) }>
    </div>
  }
}
```

I guess if nothing else the compiler could raise an error if enums aren't intended to be used like this?

**Comment by s0kil** [comment]
@jansul That actually looks like a bug, @gdotdesign could comment more on this, as I'm not exactly sure.

#### Here is another way to do this:
```mint
record FormField {
  formName : String,
  formValue : String
}

store Form {
  state values : Map(formName, formValue) = Map.empty()

  fun getFormValue (field : String) {
    values
    |> Map.getWithDefault(field, "")
  }

  fun setFormValue (field : String, value : String) {
    next
      {
        values =
          values
          |> Map.set(field, value)
      }
  }
}

component Main {
  connect Form exposing { getFormValue, setFormValue }

  fun handleOnChange (field : String, event : Html.Event) {
    Dom.getValue(event.target)
    |> setFormValue(field)
  }

  fun render : Html {
    <div>
      <label for="field1">
        <{ getFormValue("field1") }>
      </label>

      <input
        id="field1"
        name="field1"
        value={getFormValue("field1")}
        onChange={handleOnChange("field1")}/>

      <label for="field2">
        <{ getFormValue("field2") }>
      </label>

      <input
        id="field2"
        name="field2"
        value={getFormValue("field2")}
        onChange={handleOnChange("field2")}/>
    </div>
  }
}
```

**Comment by gdotdesign** [comment]
Well this is kind of a bug. 

Under the hood the `Map` implementation (https://github.com/mint-lang/mint/blob/master/core/source/Map.mint) uses JavaScripts `Map` which uses a reference check instead of the equality check of the runtime.

To make this work we would need a new implementation which uses the equality check from the runtime, or a full implementation in Mint. 

Safe values for maps are `String` and `Number` at this time.

The same goes for the `Set` type.

**Comment by s0kil** [comment]
@gdotdesign Should we support this behavior in the language?
I was thinking if we do, we could also use `enums` in other places such as when Referencing Entities:
```mint
enum InputType {
	EmailInput
	PasswordInput
}

component Main {
  fun render : Html {
    <div>
      <input as InputType::EmailInput/>
      <input as InputType::PasswordInput/>
    </div>
  }
}
```

**Comment by gdotdesign** [comment]
> Should we support this behaviour in the language?

I think we should support it at some point.

I don't understand the example you posted :) 

`<input as input/>` is for accessing a component or a DOM node so you can use it's API.

**Comment by s0kil** [comment]
Never mind, There are better ways to do what I'm trying to achieve.

**Comment by jansul** [comment]
Thanks for fixing this! :blush:
