### ISSUE TITLE
RFC: fully featured language server

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#270]
Hi there, I'm not sure if this already exists, or if it's in the pipeline, and what stage it's in... but I'm used to working with Dart which has an extremely robust language server that provides click-through support to definitions and also type information with inline documentation on hover. It also provides instant feedback as an IDE error with highlighting if you are trying to access a class member that doesn't exist. Here's a quick gif showing these features.

It would be wonderful if Mint would offer a similar feature set and if we could prioritize a VSCode plugin to handle this functionality.

![ezgif-2-35c035348d34](https://user-images.githubusercontent.com/666539/80894869-400c4c00-8cad-11ea-98ef-63c14ced701a.gif)

<img width="837" alt="Screen Shot 2020-05-02 at 7 46 53 PM" src="https://user-images.githubusercontent.com/666539/80894927-b0b36880-8cad-11ea-8c16-020cf8838d35.png">

**Comment by gdotdesign** [comment]
I've started working on this a while back in #203 also worked on it a little bit. 

It's a long task but I think it can be shipped in parts. The first one probably will be the hover info.

**Comment by lukepighetti** [comment]
@gdotdesign do we have an eta for a most basic language server? Undefined getter, class members auto-complete, and click thru would be a wonderful starting point.

**Comment by gdotdesign** [comment]
Currently my focus is mint-ui (UI library) and the language server, depending on which I have more motivation at the time.

I think the hover provider can be shipped in the first release, which is around 50% complete, so probably in a few weeks (next release). After that we need to figure out which feature of it should get more focus.

**Comment by lukepighetti** [comment]
Please ping me when you have a minimal language server that can be incorporated into `mint-vscode`
