### ISSUE TITLE
[formatting] Inconsistent output

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#273]
The output from `mint format` appears to be inconsistent, or rather, varies based on whitespace. Is this a bug or a feature?

```mint
/// original
  fun render : Html {
    <div>
      <{ greet(Person("Luke",            31)) }>
    </div>
  }

/// formatted, as expected
  fun render : Html {
    <div>
      <{ greet(Person("Luke", 31)) }>
    </div>
  }
```

```mint
/// original
  fun render : Html {
    <div>
      <{ greet(Person("Luke", 
      31)) }>
    </div>
  }

/// formatted, not as expected
  fun render : Html {
    <div>
      <{
        greet(
          Person("Luke", 31))
      }>
    </div>
  }
```

**Comment by gdotdesign** [comment]
In this case there is a new line in the call `greet(...)` that's why it formats it as a multiline call (https://github.com/mint-lang/mint/blob/master/src/formatters/call.cr#L11). 

This is logic is not implemented for record constructors (yet?), that's why it formats that in one line.
