### ISSUE TITLE
add mint to github/linguist

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#274]
Adding mint to github/linguist would enable support on GitHub for language statistics, loc counts, and (I believe) syntax highlighting via

```
` ` `mint
record Person {
  name : String,
  age : Number
}
` ` `
```

https://github.com/github/linguist

**Comment by gdotdesign** [comment]
There is already an issue for this #220, so I'm closing this in favor of that, please continue the discussion there :slightly_smiling_face:
