### ISSUE TITLE
add mint to highlight.js

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#275]
Adding `mint` to https://github.com/highlightjs/highlight.js will add support for Mint syntax highlighting to many common tools but most notably this is upstream of the Discord chat service's syntax highlighting feature.

https://highlightjs.org

**Comment by gdotdesign** [comment]
Highlightjs is used on the website, so there is a minimal version which can be used: https://github.com/mint-lang/mint-website-rails/blob/master/app/views/layouts/application.haml#L129

I'm not sure how to proceed though :slightly_smiling_face:

**Comment by gdotdesign** [comment]
I've start this in this repo https://github.com/mint-lang/highlight.js according to https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

**Comment by lukepighetti** [comment]
I believe this task is complete https://github.com/mint-lang/highlight.js/pull/1, please review.

**Comment by gdotdesign** [comment]
https://github.com/highlightjs/highlight.js/pull/2536

**Comment by lukepighetti** [comment]
Alright, so highlight.js isn't accepting new language submissions. @gdotdesign do you have any interest in changing this issue to add Mint to Prism?

**Comment by Sija** [comment]
@lukepighetti why not use a 3rd party module as it was suggested in the linked issue?

**Comment by lukepighetti** [comment]
Part of my reason for adding Mint to highlight.js is because that’s upstream from Discord’s syntax highlighting feature and I wanted to add Mint to discord’s syntax feature.

**Comment by gdotdesign** [comment]
They are not accepting new syntax definitions, so I'm closing this.
