### ISSUE TITLE
RFC: Add Websocket to core library

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#276]
I found this example of a web socket but it would be nice if it was included in the core library. 

https://sandbox.mint-lang.com/sandboxes/N0iQTG1fduXoRA

Somewhat related discussion: are platform channel implementations (back tick JS) allowed in the core library? I admit I'm not too familiar with `Crystal` or the `mint` language architecture in general.

**Comment by gdotdesign** [comment]
Yes it's my intention to move this into the core library, it just needs some clean up and some tests.

> are platform channel implementations (back tick JS) allowed in the core library?

Most of the core library is build using inline JavaScript (``` `` ```) if that's what you mean. The core library is in this repo as well https://github.com/mint-lang/mint/tree/master/core

**Comment by gdotdesign** [comment]
It's added with the #286 PR.
