### ISSUE TITLE
[feature] mint clean

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#277]
Would be nice to have a CLI subcommand `mint clean` to perform any cleaning tasks such as deleting the `dist` folder. Thoughts?

**Comment by gdotdesign** [comment]
We can have that, it's pretty trivial to implement. 

Other than the `dist` folder there are two other directories which have artifacts: `.mint` (project related packages) and `/tmp/mint-packages` (all packages) I don't know if we want to have a command to clear them.

**Comment by s0kil** [comment]
`mint clean` for project related tasks `mint clean --all` to clean globally (`/tmp`)?

**Comment by s0kil** [comment]
Seems like `--global` makes more sense for cleaning global directories.
