### ISSUE TITLE
RFC: mint format that takes text as arguments

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#278]
The way we currently handle formatting in `mint-vscode` is to copy a file to `tmp`, run `mint format /tmp/myfile.mint`, then read the file and pass it to VSCode.

I'm requesting a feature that allows us to pass a string to `mint format` and have it respond with the formatted result as a string.

This is honestly a minor improvement over what we have now, but it should reduce the format command response time from ~600ms to ~50ms and reduce the chance of collisions in naive implementations.

Any thoughts?

**Comment by s0kil** [comment]
I have thought about this yesterday, and the conclusion is that the language server will also be responsible for formatting code.

We will not need to call `mint format` directly.

**Comment by gdotdesign** [comment]
It should not be a big feature and it comes handy some times (formatting the sandbox code for example).

We should use a flag like `--stdin` to specify inline formatting.
