### ISSUE TITLE
Tree shaking (dead code elimination)

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#279]
There was interest expressed for tree shaking here: https://github.com/mint-lang/mint/issues/70#issuecomment-412427949

This issue is intended to cover that feature, which I think would be a very compelling one.

**Comment by s0kil** [comment]
This was implemented in https://github.com/mint-lang/mint/pull/98

**Comment by lukepighetti** [comment]
Wow! Great, thanks for fast response.
