### ISSUE TITLE
Installation doesn't work without Crystal installed

### ISSUE THREAD

**Issue by bmakuh** [mint-lang/mint#28]
Following [the instructions to install](https://www.mint-lang.com/install) without having Crystal installed results in this error on macOS 10.13.4.
```
$ mint
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib
  Referenced from: /usr/local/bin/mint
  Reason: image not found
Abort trap: 6
```

Installing Crystal from homebrew solves the problem.

**Comment by gdotdesign** [comment]
Thank you for creating this issue! :+1: 

Added instructions to install Crystal on Mac OSX https://github.com/mint-lang/mint-website/commit/fb6c95e58c8ab0e2ab7b94cf85110cf5c178a86c

![screenshot from 2018-06-06 08-38-13](https://user-images.githubusercontent.com/302692/41020990-2615a728-6965-11e8-9608-3ef30773e923.png)

**Comment by Acciaiodigitale** [comment]
I have Crystal on Mac but I have the same problem:

```
$ crystal -v                                                                                                                                                                          
Crystal 0.28.0 (2019-04-24)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

```
$ mint -v                                                                                                                                                                                
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib
  Referenced from: /usr/local/bin/mint
  Reason: image not found
[1]    16841 abort      mint
```

**Comment by Acciaiodigitale** [comment]
But it function compiled from source
