### ISSUE TITLE
document record keys

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#280]
Let's say we have a REST API that returns the following JSON object

```json
{
  "id": 1,
  "created_at": "2006-10-09T19:51:01.000Z",
}
```

The record might look something like this

```mint
record Item {
  id : Number,
  createdAt : Time
}
```

But as far as I know, there is no way to specify toJson/fromJson keys. Something like this might be nice...

```mint
record Item {
  id : Number,
  createdAt : Time keyed created_at
}
```

Or alternatively

```mint
record Item {
  id : Number,
  get createdAt : Time { created_at }
}
```

Any thoughts?

**Comment by s0kil** [comment]
Is [this](https://github.com/mint-lang/mint-realworld/blob/master/source/Entities/Article.mint#L11) what you are asking about? We do not have that documented yet.

**Comment by lukepighetti** [comment]
This appears to make the formatter unresponsive, should I open a new issue and close this one?

```mint
record Item {
  id : Number,
  createdAt : Time using created_at
}
```

**Comment by lukepighetti** [comment]
Looks like it's documented here: https://www.mint-lang.com/guide/reference/javascript-interop/decode-expression
