### ISSUE TITLE
Incomplete documentation for `Maybe`

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint#281]
The Documentation on `Maybe` appears to be incomplete.

https://www.mint-lang.com/api/enums/Maybe

It does not appear to include the function `Maybe.toResult(String)`

Is there a reason why it's missing? As far as I know this documentation is generated by the doc server.

**Comment by gdotdesign** [comment]
There is an enum and a module named `Maybe` https://www.mint-lang.com/api/modules/Maybe
