### ISSUE TITLE
web site & documentation fail to note that this is a language that compiles to JavaScript

### ISSUE THREAD

**Issue by masukomi** [mint-lang/mint#30]
kinda... leaving out the most important bit there. 

In fact, the word JavaScript appears exactly zero times in the main web page. I had to read the unit tests to be sure that's what this did because even the documentation for "build for production" fails to mention it. 

also, "front end" isn't necessarily the web. Desktop and mobile apps have a "front end" too.

**Comment by gdotdesign** [comment]
I've added a line that states "Mint is a programming language that compiles to JavaScript." in to the hero section of the main page.
