### ISSUE TITLE
Reduce root div nesting

### ISSUE THREAD

**Issue by Vechro** [mint-lang/mint#308]
![image](https://user-images.githubusercontent.com/6316604/87018354-cbd4b400-c1d9-11ea-93b2-2b9efdc81984.png)

Take a look at the divs without classes.

When compiling Mint, it creates multiple nested divs. The way it was explained to me is that the root div is necessary as its used by React and extensions may interfere with the contents of \<body>, confusing React, but the second div is used for listening events and the third div is from Main.mint (so in essence the third div is something I added myself).

I suggest combining the first and second div into one to reduce the unnecessary nesting.

**Comment by Sija** [comment]
This seems not relevant anymore, please reopen if needed.
