### ISSUE TITLE
Infinite reload with Crystal 0.35

### ISSUE THREAD

**Issue by waj** [mint-lang/mint#309]
I noticed that with Crystal 0.35 there is an error while trying to connect to the live-reload websocket, which causes the page to reload in an endless loop. The issue started to happen in 0.35 due to some changes in how websockets work within `HTTP::Server` and it now has a conflict with the `HTTP::CompressHandler`. I'll send a patch soon for the next Crystal version. In the meantime, this can be solved by disabling `gzip` in the reactor server.

**Comment by waj** [comment]
The PR is now ready: https://github.com/crystal-lang/crystal/pull/9608

**Comment by gdotdesign** [comment]
Thanks :+1: I suspect that #267 is related, and probably because of this on 0.34 the server stopped in Firefox after a while and needed to be restarted.
