### ISSUE TITLE
input value doesn't update

### ISSUE THREAD

**Issue by Massolari** [mint-lang/mint#316]
I have this code:

```
component Main {
  state name : String = ""
  
  fun setName(newName : String) : Promise(Never, Void) {
    next { name = formattedName }
  } where {
    formattedName =
      if (String.size(newName) > 3) {
        name
      } else {
      	newName
      }
  }
  
  fun handleInput (event : Html.Event) : Promise(Never, Void) {
    event.target
      |> Dom.getValue
      |> setName
  }

  fun render : Html {
    <div>
      <div>
        <input
          type="text"
          value={name}
          onInput={handleInput}
        />
      </div>
      <span><{ name }></span>
    </div>
  }
}
```

Sandbox: https://sandbox.mint-lang.com/sandboxes/hj4pOw6vSay37Q

When I type more than 3 characters in the input, my `name` state that's inside the `<span>` doesnt't change, whats is expected, but the value in the input keeps getting bigger while I type, what's isn't expected because I set the input `value` to be equals the state `name`.

![image](https://user-images.githubusercontent.com/12272702/92752801-a4c46b00-f35f-11ea-943a-e4f7832c6d34.png)

It looks like Mint don't re-renders the component if the `next` call doesn't change the state, is this the expected behaviour? If it is, how do I limit what the user types in the input?

**Comment by gdotdesign** [comment]
> It looks like Mint don't re-renders the component if the `next` call doesn't change the state, is this the expected behaviour? If it is, how do I limit what the user types in the input?

Yes it's the expected behaviour, every component in Mint is a [`PureComponent`](https://reactjs.org/docs/react-api.html#reactpurecomponent).

I suggest slicing the string like this https://sandbox.mint-lang.com/sandboxes/O7tPflFlENP3MQ (the `slice` method needs to be added to the standard library)

**Comment by Massolari** [comment]
> > It looks like Mint don't re-renders the component if the `next` call doesn't change the state, is this the expected behaviour? If it is, how do I limit what the user types in the input?
> 
> Yes it's the expected behaviour, every component in Mint is a [`PureComponent`](https://reactjs.org/docs/react-api.html#reactpurecomponent).
> 
> I suggest slicing the string like this https://sandbox.mint-lang.com/sandboxes/O7tPflFlENP3MQ (the `slice` method needs to be added to the standard library)

I see.

So, I need to slice in the `value` attribute AND in the `next` call, this isn't so good, maybe Mint should provide a way to do a [`forceUpdate()`](https://reactjs.org/docs/react-component.html#forceupdate) , this behaviour is a little confusing.

I'm willing to add a few functions that we have in Elm, `slice` is one of them, actually, it would be `left` and `right`, as in Elm, if it sounds good for everyone

**Comment by Massolari** [comment]
@gdotdesign Besides, your code is a little buggy:
![Demo](https://user-images.githubusercontent.com/12272702/92767338-65048000-f36d-11ea-9a33-da103a748e01.gif)

**Comment by Massolari** [comment]
@gdotdesign The code snippet I post on this issue is a simplification of I'm trying to do here.

This is closer https://sandbox.mint-lang.com/sandboxes/5Ot7gJfJAEyDrw

I have this `Field` that is a `input` component, it is suposed to be used in the `Main` component a few types, so it need to be generic. I have this `age` state that's typed as `String` and I made a function to remove the non-digit characters. Your solution doesn't work in this case because the `Field` component isn't re-rendered if I set a new age, but pass the formattedAge (with only digits) to my `Field` component:

![Demo](https://user-images.githubusercontent.com/12272702/92774592-042c7600-f374-11ea-952f-61e7c111d442.gif)

**Comment by gdotdesign** [comment]
> maybe Mint should provide a way to do a [`forceUpdate()`](https://reactjs.org/docs/react-component.html#forceupdate).

I totally forgot that you can already use `forcedUpdate`, I've updated the sandbox: https://sandbox.mint-lang.com/sandboxes/O7tPflFlENP3MQ

**Comment by Massolari** [comment]
@gdotdesign That's solved my problem, thanks! Maybe this scenario should be in the documentation.

If I'm willing to add functions to the core of the language what I'm suposed to do? Open an issue describing each one and, if approved, start coding?

**Comment by gdotdesign** [comment]
> If I'm willing to add functions to the core of the language what I'm suposed to do? Open an issue describing each one and, if approved, start coding?

That would be great! :slightly_smiling_face:  If you would like some feedback before implementing something, you can create an issue but it's not necessary, you can just create a PR directly if you like :+1: 

FYI I've added some new methods for the next version in this branch: https://github.com/mint-lang/mint/tree/compile-time-reflection/core/source

**Comment by Namek** [comment]
The reason why I really liked Elm was that such things wouldn't happen. The language protects you from all the JavaScript gibberish states and undefiness. So here's Mint that states to be exactly this but better. I think we need a solution to the problem so no workaround is needed.

Does this issue happen only because we use `PureComponent`:s? Maybe we could detect such situations and use `Component`:s instead. Or just automatically call `forceUpdate` somehow.  Even throwing a compiling error would be better than silently choking the issue in.

@gdotdesign Are there more similar cases like this? It would be nice to generalize this before fixing.

**Comment by gdotdesign** [comment]
> The reason why I really liked Elm was that such things wouldn't happen. The language protects you from all the JavaScript gibberish states and undefiness. So here's Mint that states to be exactly this but better. I think we need a solution to the problem so no workaround is needed.

It's not much better in Elm :sweat_smile: https://ellie-app.com/chbv6gdjcWra1

> Does this issue happen only because we use `PureComponent`:s? Maybe we could detect such situations and use `Component`:s instead. Or just automatically call `forceUpdate` somehow. Even throwing a compiling error would be better than silently choking the issue in.

Yes it only happen because of `PureComponent`. I'm not sure how we can detect such things compile time. 

We could use `PureComponent` for components that have no `state` and `Component` for components that do and maybe that would be a good compromise. Or we could have a flag like keyword for using `PureComponent`.

> @gdotdesign Are there more similar cases like this? It would be nice to generalize this before fixing.

This is the only one I know of (from the top of my head).

**Comment by Massolari** [comment]
> It's not much better in Elm 😅 https://ellie-app.com/chbv6gdjcWra1

It is much better in Elm. The way you did is not right, you are keeping the “wrong” value in the model, this is the right way: https://ellie-app.com/chg3yZx4Yfha1 and this way should work in mint too.

**Comment by gdotdesign** [comment]
> > It's not much better in Elm sweat_smile [ellie-app.com/chbv6gdjcWra1](https://ellie-app.com/chbv6gdjcWra1)
> 
> It is much better in Elm. The way you did is not right, you are keeping the “wrong” value in the model, this is the right way: [ellie-app.com/chg3yZx4Yfha1](https://ellie-app.com/chg3yZx4Yfha1) and this way should work in mint too.

The default behavior is different - they don't do checking (what `PureComponent` does), if you do that it's the same behavior: https://ellie-app.com/chgtNswKcXfa1

**Comment by Massolari** [comment]
> The default behavior is different - they don't do checking (what PureComponent does), if you do that it's the same behavior: https://ellie-app.com/chgtNswKcXfa1

that’s the point. Sure we can replicate the unexpected behavior in Elm, but you are doing it because you want. In mint the default is the unexpected behavior, and the solution isn’t simple, because it requires the knowledge of the purecomponent and an inline Javascript.

**Comment by gdotdesign** [comment]
Yes, I agree. Do you think it's good enough if we do this:
 
> We could use `PureComponent` for components that have no `state` and `Component` for components that do.

**Comment by Massolari** [comment]
Would this solution work here: https://sandbox.mint-lang.com/sandboxes/5Ot7gJfJAEyDrw ?

**Comment by gdotdesign** [comment]
> Would this solution work here: [sandbox.mint-lang.com/sandboxes/5Ot7gJfJAEyDrw](https://sandbox.mint-lang.com/sandboxes/5Ot7gJfJAEyDrw) ?

I don't know how it should work but at a glance it seems to be working correctly as is right now.

-----------

I've reverted the optimization (`PureComponent`) so `next {}` will always trigger a re-render no matter if nothing changed in state or props.

**Comment by Massolari** [comment]
> I don't know how it should work but at a glance it seems to be working correctly as is right now.

It should strip all the non-digits from the input. The input should show the same value as "Formatted age"

> I've reverted the optimization (PureComponent) so next {} will always trigger a re-render no matter if nothing changed in state or props.

That should be enough! Great!
The sandbox is using the latest version of Mint with this fix?

**Comment by gdotdesign** [comment]
> It should strip all the non-digits from the input. The input should show the same value as "Formatted age"

Yes, it will work like that.

> The sandbox is using the latest version of Mint with this fix?

No, I'll only update it when there is a new release.
