### ISSUE TITLE
Runtime error setting state from function in store

### ISSUE THREAD

**Issue by Massolari** [mint-lang/mint#319]
When setting a initial state from a function result in a component, it works with no problem:

```
record Test {
  field : String
}

component Main {
  state test : Test = emptyTest()
  
  fun emptyTest : Test {
    Test("")
  }
  
  fun render : Html {
    <div>"Test: "<{test.field}></div>
  }
}
```
Sandbox: https://sandbox.mint-lang.com/sandboxes/DQriJQWrflTocQ

But when I tried to the same thing in a store, it compiled but I got a runtime error:

```
record Person {
  name : String
}

store Person {
  state person : Person = emptyPerson()

  fun emptyPerson : Person {
    Person("")
  }
}

component Main {
  connect Person exposing { person }
  
  fun render : Html {
    <div>"Person: "<{person.name}></div>
  }
}
```
Sandbox: https://sandbox.mint-lang.com/sandboxes/o0xelPgLK0r-uw

Error:
![image](https://user-images.githubusercontent.com/12272702/93128462-e9287180-f6a5-11ea-9b6b-03b235ef687a.png)

**Comment by gdotdesign** [comment]
Probably it will have the same solution as #249
