### ISSUE TITLE
Syntax Error when using property name that has prefix "with"

### ISSUE THREAD

**Issue by StephenStrickland** [mint-lang/mint#32]
I'm playing with mint and started to create a set of Bootstrap 4 components. 

Running into a Syntax Error when I have a property called `withStyle : String` and I attempt to call the value in `fun render : Html`.

**Screenshot:**
<img width="1085" alt="screenshot 2018-06-10 18 00 39" src="https://user-images.githubusercontent.com/6843062/41206846-118609ac-6cd9-11e8-836a-a73c31b2c40b.png">

**Component Code:**
```
component BS.Button {
    property text : String = ""
    property disabled : Bool = false
    property type : String = "button"
    property withStyle : String = "primary"
    fun render : Html {
        <button disabled={disabled} class={"btn btn-" + withStyle} type={ type }>
            <{text}>
        </button>
    }
}
```

**Problem:**
It appears that the `withStyle` property is being parsed as a `with` statement

**Workaround:**
Use different verbiage for property names

**Environment:**
Mac OS - 10.12.6
Mint: v0.3.0
Crystal: v0.24.2

**Comment by StephenStrickland** [comment]
I can see the [with spec](https://github.com/mint-lang/mint/blob/d4a0513b6ed34d99047212420d894471055af243/spec/parsers/with_spec.cr) where you allow it. 

I think at a language level the `with` keyword should have a space char between the keyword and node name to provide for consistency.

**Comment by gdotdesign** [comment]
I agree :) It's an easy fix.

**Comment by gdotdesign** [comment]
It's fixed in master :tada: you can use it with the daily binary.

**Comment by StephenStrickland** [comment]
Fixed! Thank you very much!
