### ISSUE TITLE
Allow a component to receive an Array without wrapping in braces

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#33]
Currently if you want to supply an array to a Component you wrap the array in braces:

```
<OverviewItem name="BlockChain" items={["item1", "item2"]}/>
```

It would be nice to supply the array directly - in the same way a string works:

```
<OverviewItem name="BlockChain" items=["item1", "item2"]/>
```

**Comment by gdotdesign** [comment]
Should be out in the daily build in a few minutes.
