### ISSUE TITLE
Array.range() issue ?

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#330]
I've facing a strange issue with `Array.range()`

The following will render a sequence from 1 to 40 with a step of 2 ( using `Array.range(0, 20)` ) :

[Sandbox reproduction](https://sandbox.mint-lang.com/sandboxes/rqyhTNcq_oKITw)

```mint
enum Page {
  Index
}

store Application {
  state page : Page = Page::Index
}

component Main {
  connect Application exposing { page }

  fun render : Html {
    <div>
      case (page) {
        Page::Index => <Page.Index/>
      }
    </div>
  }
}

component Page.Index {
  fun render : Html {
    <div>
      for (i of Array.range(0, 20)) {
        <{ " #{i} " }>
      }
    </div>
  }
}
```

Not sure where the issue really is...

**Comment by gdotdesign** [comment]
This is a strange one, for example changing it so it's logged `Debug.log(Array.range(0, 20))` makes it increase by 1. This is definitely a bug I'll try to figure it out.

**Comment by gdotdesign** [comment]
I've found the cause, the `Array.range` function compiles to this in this case:
```
e(i, h) {
  return (Array.from({
      length: (h + 1) - i
  }).map((v, i) => i + i))
}
```
Notice the `i` variable which is the parameter of the function and it's in the `map` function as well.

All parameters are using names from the alphabet and are generated sequentially and in this case it conflicted with the inlined `i` variable.
