### ISSUE TITLE
"Record Partial" issue

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#332]
I tried to use Records and Partials and i have come across this issue : [sandbox](https://sandbox.mint-lang.com/sandboxes/GUArZ5WIdqvutQ)

The example provided by the guide fail :

```mint
record User {
  name : String,
  age : Number,
  active : Bool
}

partial =
    User("John Doe", 32)

partial(true) == {
  name = "John Doe",
  active = true,
  age = 32
}
```
Partial execution fail with `The function you called takes 0 arguments, while you tried to call it with 1`

Partial function type seems wrong, if i make it failed on purpose :

```mint
fun componentDidMount : Promise(Never, Void) {
  User("John Doe", 32)
}
```

I get `Function(Bool)`

Should not this be `Function(Bool,User)` ?

Tested on master branch too

**Comment by gdotdesign** [comment]
Thanks for reporting :+1: It seems that this might be a regression, and it's definitely a bug!

The example as is should work, and possible it did work when it was written but I'm not sure.

> Partial function type seems wrong, if i make it failed on purpose :
> 
> ```
> fun componentDidMount : Promise(Never, Void) {
>   User("John Doe", 32)
> }
> ```
> 
> I get `Function(Bool)`
> 
> Should not this be `Function(Bool,User)` ?

Yes it should be be `Function(Bool, User)`.
