### ISSUE TITLE
Migrating from Travis CI to Github Actions

### ISSUE THREAD

**Issue by gdotdesign** [mint-lang/mint#333]
It will be harder to use Travis CI for builds for open sources projects, so we should migrate the builds to Github Actions.

https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions

**Comment by Sija** [comment]
Why is it? Travis still offers support (and will do so in the future) for OSS repos.

**Comment by gdotdesign** [comment]
1. https://travis-ci.org/ will go into read only mode on December 31, 2020. Any projects till running there needs to be migrated to https://travis-ci.com/ using the free plan which as 1000 minutes for free.
2. It would be better to have the CI on Github as well: one less integration, it's free for public repositories

More information here: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

**Comment by gdotdesign** [comment]
Now the CI is running on Github Actions:
https://github.com/mint-lang/mint/actions
