### ISSUE TITLE
Self referencing as Component

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#337]
The context is that i need to maintain an array of components, let's call this `Items` ( [sandbox](https://sandbox.mint-lang.com/sandboxes/zccX-UtaGEDbAw) )

Since the number of `Items` is dynamic, i don't find the usual [component referencement](https://www.mint-lang.com/guide/reference/components/referencing-entities) a good fit

So, here is how i currently push them :
```mint
component Item {
  fun componentDidMount {
    Store.add(`this`)
  }
}
```

My question is, **do we have a "Mint way" to get current component reference** ?
I'm thinking of a **special property** or a **lifecycle functions parameters**, for example

I've also notice browser warnings when comparing components (i probably should separate this issue, let me know) :
```
state items : Array(Item) = []
[...]
Array.indexOf(item, items) // This throw the warning
```
`Comparing entites with === because there is no comparison function defined`

**Comment by gdotdesign** [comment]
Can you provide more information about why are you doing this? I would like to understand the underlying problem.

> My question is, **do we have a "Mint way" to get current component reference** ?
> I'm thinking of a **special property** or a **lifecycle functions parameters**, for example

No there is no special keyword or something like that. Also the `Item` type might not refer to the component itself, like a reference would (components don't have an exposed typed).

**Comment by Eternahl** [comment]
> Can you provide more information about why are you doing this? I would like to understand the underlying problem

I'm trying to **update the internal state** of `Components` from a `Store`
Since `Components` states are privates, i'm using a `Component` method to update them
To be able to perform this, i need a way to maintain a list of this `Components` in my `Store`

**Comment by gdotdesign** [comment]
> I'm trying to **update the internal state** of `Components` from a `Store`

Your way can work or if you really need to keep track of components you can create a provider instead: 
https://sandbox.mint-lang.com/sandboxes/jZWHX--U0P3REw

---------------

Side note: I probably don't have enough context here but from what I can see is that you are taking an imperative approach to this, I would suggest that you turn this around and try to make it declarative by having the data in the store and change it there which would re-render the components with the new data.

**Comment by Eternahl** [comment]
> if you really need to keep track of components you can create a provider instead

@gdotdesign 
You were right, using Providers to be more declarative was the good fit
Thanks for your time
