### ISSUE TITLE
Confusing error in NextCallStateTypeMismatch

### ISSUE THREAD

**Issue by matthewmcgarvey** [mint-lang/mint#339]
<img width="558" alt="CleanShot 2020-11-28 at 12 06 29@2x" src="https://user-images.githubusercontent.com/17329408/100522954-37f88a00-3172-11eb-9221-1132ddff396e.png">

I get that the error is because the value being assigned to state doesn't match the type but the error message doesn't make any sense.

https://github.com/mint-lang/mint/blob/f1b79d086e532b31433b9745145f1015c8db23f5/src/messages/next_call_state_type_mismatch.cr#L4-L9

**Comment by Sija** [comment]
@matthewmcgarvey Could you provide failing code example?

**Comment by matthewmcgarvey** [comment]
@Sija  https://sandbox.mint-lang.com/sandboxes/b7sVpfRO2_eJSQ

**Comment by Namek** [comment]
The message could be improved. Can you suggest maybe, how would you see that error?

**Comment by gdotdesign** [comment]
I would suggest something like:
 
```
You were trying to assign an incompatible value to the status state.

The type of the state is:

String

But the type you are trying to assign to it is:

Number

Here is where you did the assignment:

SNIPPET TO THE NEXT CALL

And here is where the state is defined:

SNIPPET TO THE STATE DEFINITION
```
