### ISSUE TITLE
Add Mint to Wappalyzer

### ISSUE THREAD

**Issue by faustinoaq** [mint-lang/mint#34]
Ref: https://github.com/AliasIO/Wappalyzer

**Comment by faustinoaq** [comment]
As @gdotdesign said before, we can use `Mint` keyword on generated js bundles

**Comment by faustinoaq** [comment]
> Only widely used applications should be added. When creating a pull request, please include ten or more links to websites that use the application, a GitHub page with at least 1,000 stars or anything that will help establish the size of the user base.

Oh, looks like we need at least 100 stars on github before add it to wappanalyzer :sweat_smile: 

Ref: https://www.wappalyzer.com/docs

**Comment by gdotdesign** [comment]
Well we reached 1000 stars :wink:

**Comment by wisn** [comment]
@gdotdesign as a starter, we should add `<meta generator="mint">` or something like that before adding Mint to Wappalyzer. That would easier for us to add Mint to Wappalyzer.

**Comment by gdotdesign** [comment]
Closing this since the docs link is out of date and it's not relevant anymore.
