### ISSUE TITLE
Support property value interpolation in "CSS At-rules"

### ISSUE THREAD

**Issue by Eternahl** [mint-lang/mint#340]
I'm trying to use _CSS_ value interpolation in "_CSS_ at-rules", but it fail ( [sandbox](https://sandbox.mint-lang.com/sandboxes/ErhbFJ8DXniWUQ) )
```mint
@media (min-width: #{mediumSize}px) { ... }
```
Fails with :
`The body of a at rule must end with a closing bracket.`
`I was looking for the bracket "}" but found "mediumSize}px)" instead. `

**Comment by gdotdesign** [comment]
Unfortunately this is not possible, I'll try to explain why.

Dynamic values in the compiler are done using [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) so everything compiles **static CSS**, and all dynamic values are set in JavaScript.

The main issue is that CSS variables are not usable in media queries: https://www.jmptr.com/blog/css-variables/

So to implement this we would need to change how CSS generation works so it would generate the CSS dynamically and that would cause some issues, probably paint flashing and some visual glitches.

-----------

An alternative is to use a provider where it's possible to do dynamic queries:
```
state mobile : Bool = false
state breakpoint : Number = 900

use Provider.MediaQuery {
  query = "(max-width: #{breakpoint}px)",
  changes =
    (value : Bool) : Promise(Never, Void) {
      next { mobile = value }
    }
}

```

**Comment by Eternahl** [comment]
@gdotdesign  That make sense, i should have understand this before asking...

However, it seems this might be achievable in the future using [CSS Environment Variables](https://github.com/w3c/csswg-drafts/issues/2627)
This post also point out an interesting alternative combining somes sort of ["CSS breakpoints" and "@supports() query"](https://github.com/w3c/csswg-drafts/issues/2627#issuecomment-548428776)

`Provider` alternative will be good enough for now !
I let you close this issue as you wish

**Comment by gdotdesign** [comment]
> @gdotdesign That make sense, i should have understand this before asking...

I think it's on me (it's not documented properly) so I'm glad that you asked :)

> However, it seems this might be achievable in the future using [CSS Environment Variables](https://github.com/w3c/csswg-drafts/issues/2627)
> This post also point out an interesting alternative combining somes sort of ["CSS breakpoints" and "@supports() query"](https://github.com/w3c/csswg-drafts/issues/2627#issuecomment-548428776)

The solution there is interesting, but it requires a lot of scripting to be viable, I would rather wait for something official, since we have a Provider workaround.
