### ISSUE TITLE
Tailwind support

### ISSUE THREAD

**Issue by thesobercoder** [mint-lang/mint#348]
I'm trying out mint and so far I'm loving it. The live code rebuilds are ridiculously fast. Would be great to see official Tailwind CSS support.

**Comment by gdotdesign** [comment]
Hi, I'm glad you like Mint :slightly_smiling_face: 

I'm not sure what you mean by official support, what you can do now is to include the compiled Tailwind CSS in either [the head file](https://www.mint-lang.com/guide/recipes/using-third-party-css) or in the `external.stylesheets` of the `mint.json`.

**Comment by iambudi** [comment]
I guess official support means ability to tree-shake unused tailwind styles (purge) and optimize build size?

**Comment by nailuj29gaming** [comment]
you can see https://www.mint-lang.com/guide/recipes/using-third-party-css for info on how to set it up

**Comment by bstro** [comment]
It is unclear to me, but it seems that the guide addresses tree-shaking unused tailwind styles. First-class Tailwind support would be a very attractive feature to me.

**Comment by gdotdesign** [comment]
> I guess official support means ability to tree-shake unused tailwind styles (purge) and optimize build size?

That's not possible at the moment because Mint does not interface with the NPM ecosystem, until it does the only option is to use a pre-build version of it.

Also it's not possible to create tailwind style utility CSS because there are no global styles.
