### ISSUE TITLE
provide detect change time flag for adjustment with auto-format

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#35]
I love the auto-format but it's a bit too quick for me - when I'm typing it doesn't give me enough time to finish what I'm doing and then it reformats - and when I'm in the middle of thinking or being a bit slow - it formats my code away.

So an optional flag that can change the delay would be nice so I can set it to be a bit slower.

What do you think?

Another option is that I add something to my editor to make use of the new format command in the cli and I manually format - this might be a good option as well - that doesn't require any code changes

**Comment by gdotdesign** [comment]
> when I'm typing it doesn't give me enough time to finish what I'm doing and then it reformats

It should only reformat when the file is changed on the disk (saved), what editor are you using?

I would go with the editor option to format the code, in Sublime for crystal it works great can do something similar probably.

**Comment by kingsleyh** [comment]
I’m using Atom - but actually I have auto save turned on in atom - I guess this is causing the problem - yep I will set my editor differently
