### ISSUE TITLE
Docs use "Wether"

### ISSUE THREAD

**Issue by wiverson** [mint-lang/mint#352]
Probably don't want to use https://www.dictionary.com/browse/wether in documentation.

Use https://www.thesaurus.com/browse/whether instead.

e.g. sample usage: https://www.mint-lang.com/packages/mint-lang/mint-ui/0.0.13/components/Ui.Button

:)

**Comment by gdotdesign** [comment]
Thanks for pointing it out :+1: I always mean the latter (whether) but I misspell it regularly :smile: and then copy past that as well :sweat_smile: 

I will close this issue after I fixed them.

**Comment by wiverson** [comment]
Oh, no worries. I noticed it in a bunch of places - English is a pain.  :)
