### ISSUE TITLE
Sometimes functions in the current module must be qualified

### ISSUE THREAD

**Issue by greg-enbala** [mint-lang/mint#372]
Bug:
In this sandbox: https://sandbox.mint-lang.com/sandboxes/HN3frS_e3GTFUg . Down on line 143, which reads: `      |> Murmur3.rotlBy(15)` . If you remove `Murmur3` from the beginning of that function call you will get a compile error that says:
```
I could not find a variable, function or property with the name: rotlBy
```

Which is strange for 2 reasons:
1) The function `rotlBy` and the current function are both defined in the Murmur3 module.
2) 3 lines down on line 146 `rotlBy` is used unqualified and it works just fine.

Expectation:
Both of the function calls to work unqualified.

**Comment by gdotdesign** [comment]
:thinking: It's an interesting bug, trying to track it down.

If I remove all references of the module `Murmur3` from inside of it it works: 
https://sandbox.mint-lang.com/sandboxes/w57ifbbXgRh8GA

But if I add at least one it doesn't:'
```
res =
  k1
  |> multiplyBy(C1)
  |> rotlBy(15)
  |> multiplyBy(Murmur3:C2) /* Added it here for the constant. */
  |> Bitwise.xor(h1)
  |> rotlBy(13)
  |> multiplyBy(5)
```

Which leaves me to believe that it's related to module access. 

I'll keep digging though :sweat_smile:
