### ISSUE TITLE
trouble using @font-face

### ISSUE THREAD

**Issue by f4tq** [mint-lang/mint#373]
`Mint 0.11.0`

Hi,
I'm new to mint but practiced at crystal.
I've been trying to get a custom font I need to load.  Nothing seems to work.
I've tried the 2 documented methods- neither work:
## Method 1  [@font-face](https://www.mint-lang.com/guide/reference/components/styling-elements)
```
component Main {
  style base {
    @font-face {
      font-family: HexAlpha;
      src: url("/fonts/HexAlpha.ttf") format("truetype");
    }
    font-family: HexAlpha;
  }
  fun render : Html {
    <div::base>
     "ABCDEFG0123456789"
    </div>
  }
}
```
### rendered style
```
<style>
.a {
  font-family: HexAlpha;
}

@font-face {
  font-family: HexAlpha;
  src: var(--a-a);
}
</style>
```
### rendered html:
```
<div><div class="a" style="--a-a:url(&quot;/fonts/HexAlpha.ttf&quot;) format(&quot;truetype&quot;);">ABCDEFG0123456789</div></div>
```
browser error:> `Unknown descriptor ‘var(’ in @font-face rule.  Skipped to next declaration.`

## Method 2 -  using head.html pointing to `/css/myexternal.css`
I attempt to reference the '@font-face' load via /css/myexternal.css

```
component Main {
  style base {
   font-family: "HexAlpha";
  }
  fun render : Html {
    <div::base>
     "ABCDEFG0123456789"
    </div>
  }
```
which renders:
style:
```
<style>
.a {
  font-family: var(--a-a);
}
</style>
```
body:
```
<div><div class="a" style="--a-a:&quot;HexAlpha&quot;;">ABCDEFG0123456789</div></div>
```

## Here is the overall project layout:

-  `mint init foo` with the font copied into project with `external css file` i.e. but internal to project

```
├── assets
│   └──  head.html
├── mint.json
├── public
│   ├── css
│   │   └── myexternal.css
│   └── fonts
│       └── HexAlpha.ttf
├── source
│   └── Main.mint
└── tests
    └── Main.mint
```

- test getting the font which works with type set to `font/ttf`

```
curl -v http://localhost:3001/fonts/HexAlpha.ttf
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3001 (#0)
> GET /fonts/HexAlpha.ttf HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< X-Powered-By: Kemal
< Content-Type: font/ttf
< Etag: W/"1613927510"
< Last-Modified: Sun, 21 Feb 2021 17:11:50 GMT
< Accept-Ranges: bytes
< X-Content-Type-Options: nosniff
< Content-Length: 17348
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
```

- Get the external `css` to set up the external css method
```
curl  http://localhost:3001/css/myexternal.css
<style type="text/css" media="screen, print">
   @font-face {
      font-family: HexAlpha;
      src: url("/fonts/HexAlpha.ttf") format("truetype");
    }
</style>
```
Kemal serves up the stylesheet/font assets as expected...

I'm not sure what else to try. Any assistance would be great.

FWIW, I cloned both github.com/mint-lang/mint and github.com/mint/mint-ui and 'grepped' the code for font-face samples/tests etc that might help.  I can't find a test though - that actually tries to load/render a font - just ones that render code...
  
Is @font-face known to work?  Is there a work around?  
Many thanks
Chris

**Comment by f4tq** [comment]
I sorted out a work-around for now in case someone needs to use there own fonts:  go completely external with css class , i.e.: `/css/myexternal.css:`

```
cat workspace/public/css/barcode.css 

@font-face {
      font-family: "HexAlpha";
      src: url("/fonts/HexAlpha.ttf") format("truetype");
}
.base {
      font-family: HexAlpha;
}
```
and Main.mint:
```
fun render : Html {
    <div class="base">
     "ABCDEFG0123456789"
    </div>
  }
```
Voila, by non-conventional font renders...
I was bewitched by using mint's style tag when regular old css worked

**Comment by gdotdesign** [comment]
Hi, thanks for creating this issue :+1: Love it how detailed it is :pray: 

There seems to be two bugs here:

1. The font-face declaration using `var(--...)`
2. The quotes are converted into HTML entities for some reason

Both should be fixable.
