### ISSUE TITLE
DataTransfer polyfill is not loaded causing events to fail in Safari

### ISSUE THREAD

**Issue by itsgreggreg** [mint-lang/mint#374]
Safari does not implement the `DataTransfer` constructor yet mint is relying on it. I believe this means all events will fail in safari with the current version of mint. To test this you can visit https://mint-todo-mvc.greg.lol in Safari and try to add or edit a todo. You will see it doesn't work, and if you open the console you will see:

![Screen Shot 2021-02-22 at 12 08 41 PM](https://user-images.githubusercontent.com/6858318/108751042-5c60ca00-7507-11eb-8d2f-65e399d78858.jpg)

Checking the page sources we see:
![Screen Shot 2021-02-22 at 12 11 43 PM](https://user-images.githubusercontent.com/6858318/108751081-671b5f00-7507-11eb-808b-60bb8ef6877f.jpg)

Checking MDN we can see that it is not provided in Safari:
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/DataTransfer#browser_compatibility

There appears to be a pollyfill here: https://github.com/mint-lang/mint-runtime/blob/7e2d0716a7be998b078f031ba6d7b8d46fc12ba0/source/Utils.js#L46

But it is not added to the javascript generated by Mint.

**Comment by gdotdesign** [comment]
Hi, thanks for reporting this is fixed in master and it will be released with 0.12.0.
