### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by ghost** [mint-lang/mint#384]
I was searching the docs for any benchmarks or comparisons of an application written in Mint, with other modern frameworks, like Svelte or Vue, but i couldn't find anything, this could be fairly useful, especially for enthusiasts or people who are interested in the project and considering giving it a try, but have concerns about performance and/or size

**Comment by gdotdesign** [comment]
I agree, it would be great to have a direct comparison - I'll put it on my todo list :slightly_smiling_face: 

To answer the points you raised:
* performance - Mint uses Preact under the hood so any benchmark that compares Preact to the other frameworks should apply here as well.
* size - Mint has dead code elimination built in so only what is used goes into the bundle. When moving from React to Preact I created a blog post that shows some bundle sizes (styles included) https://www.mint-lang.com/blog/mint-0.8.0

**Comment by gdotdesign** [comment]
At this point it is not relevant to Mint since it uses Preact so I'm closing this issue.
