### ISSUE TITLE
[Mac M1] Brew install error "The x86_64 architecture is required for this software"

### ISSUE THREAD

**Issue by pqkluan** [mint-lang/mint#386]
I tried to install mint-lang on Mac mini m1 and encountered the following error:

```zsh
$ brew install mint-lang
==> Installing mint-lang from mint-lang/mint-lang
llvm@9: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.
```

I googled the issue but found no related topic for this bug. 
Any advice?

**Comment by nailuj29gaming** [comment]
You can build it from source for now.

**Comment by pqkluan** [comment]
Thank you @nailuj29gaming, I'll try to build it from source.

**Comment by gdotdesign** [comment]
This will be fixed once Crystal is supported natively https://github.com/crystal-lang/crystal/issues/10237 (keeping this issue open until it is supported)

**Comment by pqkluan** [comment]
> This will be fixed once Crystal is supported natively [crystal-lang/crystal#10237](https://github.com/crystal-lang/crystal/issues/10237) (keeping this issue open until it is supported)

Yup, I tried to build from source but it require Crystal lang (which also throw the same error).
I'm haven't try the docker image yet, since I feel it's been too much a hassle for trying mint-lang at the moment.
