### ISSUE TITLE
Type checking message error

### ISSUE THREAD

**Issue by phillipnunes** [mint-lang/mint#388]
I've been testing the type checking, so I made this change on purpose in my component:
`fun render : HTML {`

Instead of:
`fun render : Html {`

But I em getting this message error (I think it's inverted):
"The return type of a function does not match it's type definition.

I was expecting:
**HTML**

Instead it is:
**Html**"

Is it not supposed to be the inverse? Something like:

"I was expecting:
**Html**

Instead it is:
**HTML**"

**Comment by gdotdesign** [comment]
Yes, this is probably a bug.

**Comment by gdotdesign** [comment]
After reviewing this again to fix it I realized that this is not a bug.

In this example
```
fun render : HTML {
  <div></div>
}
```

The type checker first checks if the return type of the function matches the type of the body. In this case the expected type is the return type so `HTML` while the type of the body is `Html`.

There is an other type error (what I think you expected) if the `render` functions type does not match `Html`:

```
fun render : Time {
  Time.now()
}
```

![image](https://user-images.githubusercontent.com/302692/114422290-6cfff900-9bb6-11eb-995a-91d6c13b83c9.png)

To get here the function itself needs to be type sound.
