### ISSUE TITLE
Window.open always results in ReferenceError: url is not defined

### ISSUE THREAD

**Issue by rideron89** [mint-lang/mint#390]
Hello,

I cannot get the `Window.open()` method to work. I receive the following warning in the developer console:

```
index.js:990 Unhandled error in sequence expression:
index.js:991 ReferenceError: url is not defined
    at Object.ak (index.js:385)
    at index.js:987
```

The compiled code in index.js at line 385 looks like this:

```javascript
const AV = new(class extends _M {
  ak(au) {
    return (window.open(url));
  }
});
```

I am using the following function code:

```
fun showTdaWindow() {
    sequence {
        params = SearchParams.empty()
            |> SearchParams.append("client_id", @TDA_CLIENT_ID)
            |> SearchParams.append("redirect_uri", @TDA_REDIRECT_URI)
            |> SearchParams.append("response_type", "code")
            |> SearchParams.toString

        url = "https://auth.tdameritrade.com/auth?" + params

        Window.open(url)
    }
}
```

My first thought was I was using `url` wrong, but even using `Window.open("https://www.google.com")` results in the same exact error message.

If I try to catch `ReferenceError`, Mint warns me that nothing is throwing it.

**Mint version**: 0.12.0-devel

Thanks.

**Comment by gdotdesign** [comment]
Hi :wave: Thanks for creating such a detailed issue :+1: 

This is a bug in the function, the `url` variable is not interpolated here:
https://github.com/mint-lang/mint/blob/master/core/source/Window.mint#L168

It should be a quick fix, until that you can use inline JavaScript
```
`window.open(#{url})`
``` 
instead of
```
Window.open(url)
```
