### ISSUE TITLE
TypeError: Illegal constructor

### ISSUE THREAD

**Issue by abedurftig** [mint-lang/mint#392]
Hello ✋ 

First of all. Thank you for this great project. The promises sound great and I really like the idea. I tried to get the run the "Counter" example from the website. While it works in Chrome it does not in Safari and in the console I see the following error, when trying to increment for example.

`TypeError: Illegal constructor`

I am using Mint 0.11.0.

Main.mint

```
component Main {
  style base {
    font-family: sans;
    font-weight: bold;
    font-size: 50px;

    justify-content: center;
    align-items: center;
    display: flex;
    height: 100vh;
    width: 100vw;
  }

  fun render : Html {
    <div::base>
      <Counter/>
    </div>
  }
}
```
Counter.mint
```
component Counter {
  state counter = 0

  fun increment {
    next { counter = counter + 1 }
  }

  fun decrement {
    next { counter = counter - 1 }
  }

  fun render {
    <div>
      <button onClick={decrement}>
        "Decrement"
      </button>

      <span>
        <{ Number.toString(counter) }>
      </span>

      <button onClick={increment}>
        "Increment"
      </button>
    </div>
  }
}
```

Here is the stack trace from the console.
```
[Error] TypeError: Illegal constructor
	(anonymous function) (index.js:1:40998)
	get (index.js:1:40998)
	e (index.js:59:1803)
	e
	_normalizeEvent (index.js:7)
	onClick (index.js:61:211)
	x (index.js:1:4013)
```

**Comment by gdotdesign** [comment]
Thanks for opening this issue! :pray: 

It's the same issue as https://github.com/mint-lang/mint/issues/374#issuecomment-783865805 which is fixed in master.

**Comment by abedurftig** [comment]
Thanks for getting back so promptly. I will close this issue then.
