### ISSUE TITLE
Type parameters are missing from types in error messages 

### ISSUE THREAD

**Issue by nilslindemann** [mint-lang/mint#403]
In this code ...

```
component Main {
  fun purr (name : String) : String {
    name + ": purr purr"
  }

  fun does (name : String, action : Function(String, Html)) {
    action(name)
  }

  fun render {
    does("Garfield", purr)
  }
}
```

... the second parameter of the `does` function has a wrong type, it should be `Function(String, String)`. `does` also has no return type defined.

This leads to the following error message:

```
The 2nd argument to a function is causing a mismatch.

The function is expecting the 2nd argument to be:

Function(String)

Instead it is:

Function(String)

The type of the function is:

Function(String)
```

When I add a return type `String` to the `does` function, then the error message is better. But it selects the whole `does` function. I wonder, shouldn't it just select the `Function(String, Html)` part?

Sorry for posting so much issues and making no pulls. I do not understand the parser code good enough. Actually I do not even know which language this is :-)

**Comment by gdotdesign** [comment]
I think the proper error messages would be this:

```
The 2nd argument to a function is causing a mismatch.

The function is expecting the 2nd argument to be:

Function(String, Html)

Instead it is:

Function(String, String)

The type of the function is:

Function(String, Function(String, Html), Html)
```

I've noticed this as well, for some reason only the first type parameter is printed in error messages like this so this is definitely a bug.

> Sorry for posting so much issues and making no pulls. I do not understand the parser code good enough. Actually I do not even know which language this is :-)

No worries, it's good feedback, keep it coming!

**Comment by nilslindemann** [comment]
Thats awesome! It is even on the website now! Thank you!

**Comment by nilslindemann** [comment]
You know, i need this on the website or in the binary, because i am currently having problems installing it from sources. See next issue, hehe.
