### ISSUE TITLE
shards install gives incompatible dependencies when installing from sources

### ISSUE THREAD

**Issue by nilslindemann** [mint-lang/mint#404]
In order to be up to date with changes made in this repo, i was just trying to install Mint from sources.

I installed the [Crystal](https://github.com/crystal-lang/crystal/releases/download/1.0.0/crystal-1.0.0-1-linux-x86_64.tar.gz) compiler [this](https://crystal-lang.org/install/from_targz/) way (and not [this](https://crystal-lang.org/install/on_linux_mint/) way because of [this](https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html)), on a recent Linux Mint.

I added two symlinks to crystal and shards.

```
ln -s /home/nils/run/crystal-1.0.0-1/bin/crystal /usr/local/bin/crystal
ln -s /home/nils/run/crystal-1.0.0-1/bin/shards /usr/local/bin/shards
```

After doing this, `crystal --version` gives 1.0.0, and `shards --version` gives 0.14.1.

Now i proceeded as described [here](https://www.mint-lang.com/install) -> _Install from source_, but the third command, `shards install` gives the following output and i am not sure how to proceed (Crystal is new for me). Should i use `--ignore-crystal-version` or should i try to update these seemingly incompatible shards, and if so, how do i do this? Any hints appreciated.

Here is the output of `shards install`:

```
nils@eve:~/run/mint$ shards install
Resolving dependencies
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/schovi/baked_file_system.git
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/jwaldrip/admiral.cr.git
Fetching https://github.com/gdotdesign/tree_template.git
Fetching https://github.com/vladfaust/time_format.cr.git
Fetching https://github.com/gdotdesign/cr-dotenv.git
Fetching https://github.com/icyleaf/markd.git
Fetching https://github.com/crystal-ameba/ameba.git
Fetching https://github.com/makenowjust/crystal-diff.git
Unable to satisfy the following requirements:

- `crystal (~> 0.23, >= 0.23.1)` required by `string_inflection 0.2.1`
- `crystal (>= 0.35.0)` required by `baked_file_system 0.10.0`
- `crystal (>= 0.36.0)` required by `kemal 1.0.0`
- `crystal (>= 0.34.0)` required by `admiral 1.11.4`
- `crystal (< 1.0.0)` required by `tree_template 0.1.0+git.commit.7e24c92208cc99938f3fbd8f5fecda22bcbe3cc3`
- `crystal (~> 0.24, >= 0.24.2)` required by `time_format 0.1.1`
- `crystal (>= 0.34.0, < 2.0.0)` required by `dotenv 1.0.0`
- `crystal (~> 1.0, >= 1.0.0)` required by `markd 0.4.0`
- `crystal (>= 0.35.0)` required by `ameba 0.14.2`
- `crystal (< 1.0.0)` required by `diff 1.1.0`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```

**Comment by Sija** [comment]
> Should i use `--ignore-crystal-version`

@nilslindemann yup

**Comment by nilslindemann** [comment]
```
shards install --ignore-crystal-version
```

**ERROR** "cannot find -lyaml (this usually means you need to install the development package for **libyaml**) (...)"

```
sudo apt-get install libyaml-dev
shards install --ignore-crystal-version
```

**ERROR** "cannot find -levent (this usually means you need to install the development package for **libevent**) (...)"

```
sudo apt-get install libevent-dev
shards install --ignore-crystal-version
```

DONE

```
crystal build src/mint.cr -o mint -p --release --no-debug
```

*wait 30 minutes*

**ERROR** "cannot find -lxml2 (this usually means you need to install the development package for **libxml2**) cannot find -lssl (this usually means you need to install the development package for **libssl**) cannot find -lcrypto (this usually means you need to install the development package for **libcrypto**) cannot find -lcrypto (this usually means you need to install the development package for **libcrypto**) (...)"

OH COME ON

```
sudo apt-get install libxml2-dev
sudo apt-get install libssl-dev
```

*[libcrypto is already contained in libssl-dev](https://stackoverflow.com/a/14364669/1658543)*

```
crystal build src/mint.cr -o mint -p --release --no-debug
```

*wait 30 minutes*

DONE

```
chmod +x ./mint
sudo mv ./mint /usr/local/bin/mint
cd ~/code
mint init helloworld
cd mint
mint install
mint start
```

http://127.0.0.1:3000/

"Edit source/Main.mint and save to reload."

:-)

**Comment by nilslindemann** [comment]
Thanks, @Sija, i succeeded.

I had to install three extra packages `libyaml-dev`, `libevent-dev`, `libxml2-dev` and `libssl-dev` on my way. To anyone reading this, I recommend to check if these are installed _before_ you run the build command, because this needs very long (30 minutes on my machine) and it will not report these missing packages at the beginning but at the end ;-)

**Comment by nilslindemann** [comment]
Haha, 404, that issue number fits :-)

**Comment by matthewmcgarvey** [comment]
Once all these PRs are in, there should be no Crystal version issues:

- https://github.com/mint-lang/mint/pull/421
- https://github.com/mint-lang/mint/pull/423
- https://github.com/mint-lang/mint/pull/424
- https://github.com/mint-lang/mint/pull/425

**Comment by matthewmcgarvey** [comment]
@Sija if you want to unpin this, it is no longer an issue

**Comment by Sija** [comment]
@matthewmcgarvey Good point, done!
