### ISSUE TITLE
Feature request: mint lint command

### ISSUE THREAD

**Issue by Daniel-Knights** [mint-lang/mint#405]
No idea how doable this is, but, a command like `mint lint` that returns all errors in a Mint project would be really useful. 

Reason being, I'd like to add linting/diagnostics to the VSCode extension, but, without a command like this, I'd need to parse every document separately and essentially reimplement Mint's error-handling from scratch. I could hack something together using `mint compile`, but, being able to run `mint lint` and get the results in a clean, readable format would make things 10x easier and would mean that the extension stays up-to-date with Mint's compiler.

**Comment by gdotdesign** [comment]
It's not that hard to implement a `lint` command, we just need to figure out what should it do.

In brief this is how the errors work in Mint currently: 

1. We try to parse the `mint.json` file and if it has errors we show that and stop.
2. We go through each source and if we encounter an error we show that and stop.
3. We try to type check the whole application and if we encounter an error we show that and stop.

So basically we are only showing one error at a time. 

I guess what you would like to have (and please confirm) is:

- the error from the `mint.json` file
- parse errors from all files
- the first type error if there is one

Other considerations: 

- it should have optionally a JSON output
- it should return exit code 1 of there are any errors so it can be included in CI/CD
- it can run checks for the formatting as well on any files that doesn't have any parse errors
- it should be a separate class for reusability (for the language server)

By the way this will be essentially the diagnostics information for the language server as well.

----------------

This is a good first issue for someone who wants to contribute to the project, the `compile` command can be a good reference: https://github.com/mint-lang/mint/blob/master/src/commands/compile.cr

**Comment by Daniel-Knights** [comment]
That'd be perfect @gdotdesign. I would volunteer to make a pull request, but I don't have any experience with Crystal. I might fork the repo and give it a go, but no promises 😅
