### ISSUE TITLE
Replace tree_template dependency with ECR

### ISSUE THREAD

**Issue by matthewmcgarvey** [mint-lang/mint#422]
https://github.com/gdotdesign/tree_template is not updated to support Crystal 1.0.0. It's owned by @gdotdesign so it would be trivial to get it updated but I was wondering if it might be better to consider switching to ECR?

It's definitely a preference thing with choosing to build HTML with Crystal, but since this functionality isn't for users of mint and is only used in 2 places ([here](https://github.com/mint-lang/mint/blob/29df622d06feb1ad822cec5400dac9153203bcae/src/sandbox_server.cr#L96-L113) and [here](https://github.com/mint-lang/mint/blob/29df622d06feb1ad822cec5400dac9153203bcae/src/utils/index_html.cr#L25-L107)) maybe it would be better for two simple reasons:
- It's included in Crystal's standard library so it will always be up to date and removes a dependency
- it's more performant than an HTML dsl in crystal

**Comment by gdotdesign** [comment]
I think it's a good idea, less dependencies are the better :+1:

**Comment by matthewmcgarvey** [comment]
I'll try to do this 👍
