### ISSUE TITLE
Should `Http.jsonBody` also set `Content-type` header

### ISSUE THREAD

**Issue by tkshnwesper** [mint-lang/mint#432]
Hello,

I stumbled across this while using the `Http.jsonBody` method. Would it be a good idea to set `Content-type` as `application/json` when `Http.jsonBody` is called?

https://github.com/mint-lang/mint/blob/df3ac8b3ef81a2f3a5e46ccc09d8a1b3cd16066e/core/source/Http.mint#L155

**Comment by Sija** [comment]
Sounds pretty sensible to me, same goes for `Http.formDataBody`.

**Comment by tkshnwesper** [comment]
Cool, for `Http.formDataBody` `application/x-www-form-urlencoded` should be set, right?

**Comment by Sija** [comment]
@tkshnwesper More like `multipart/form-data`, although I've found a warning suggesting against it on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects):

> **Warning**: When using FormData to submit POST requests using `XMLHttpRequest` or the `Fetch_API` with the `multipart/form-data` Content-Type (e.g. when uploading Files and Blobs to the server), _do not_ explicitly set the `Content-Type` header on the request. Doing so will prevent the browser from being able to set the Content-Type header with the boundary expression it will use to delimit form fields in the request body.

**Comment by tkshnwesper** [comment]
Yes, I think you are right, @Sija. Thank you!

**Comment by gdotdesign** [comment]
> Cool, for `Http.formDataBody` `application/x-www-form-urlencoded` should be set, right?

It depends you need `multipart/form-data` if the payload contains files.
