### ISSUE TITLE
Show suite name in the test failure output

### ISSUE THREAD

**Issue by matthewmcgarvey** [mint-lang/mint#433]
I was looking at the test failures for https://github.com/mint-lang/mint/pull/429 and the test failure output looks like this:
<img width="310" alt="CleanShot 2021-05-22 at 09 53 21@2x" src="https://user-images.githubusercontent.com/17329408/119228972-9bd98b00-bae3-11eb-9607-da555b18dbbb.png">

Because I wasn't sure if the test output was like Crystal/Ruby's specs where it appends `it` I searched the test suite or "returns the value" and there was 21 matches across 9 files. In order to actually find the test failures I had to run the test suite with documentation formatting to actually see the suite name.

Could there be a test failure output that incorporates the suite name?

Maybe...

Before:

```
439 tests
  ➔ 437 passed
  ➔ 2 failed
    it returns the value
    |> Assertion failed copy != none
    it returns the value
    |> Assertion failed copy != none
```

After:

```
439 tests
  ➔ 437 passed
  ➔ 2 failed
    Html.DataTransfer.setEffectAllowed
    - it returns the value
      |> Assertion failed copy != none
    Html.DataTransfer.setDropEffect
    - it returns the value
      |> Assertion failed copy != none
```

**Comment by Sija** [comment]
Haha, I was just about to open a ticket for that, @matthewmcgarvey you beat me to it :D
