### ISSUE TITLE
Display the filename and the source line of the failed test

### ISSUE THREAD

**Issue by Sija** [mint-lang/mint#441]
Right now the failing tests are shown with just the name (and a suite name, so that's better already), which makes navigating to them a bit hard at a times. IMO showing the filename along with the line number would be of an immense help in that regard.

Followup to #436

**Comment by Sija** [comment]
I've ended up hitting a road block at: https://github.com/mint-lang/mint/blob/3389a71fa92a60ed38e89796bdf3d1b884885aed/src/compilers/test.cr#L3-L41

We can get the filename easily from `node.input.file`, but I can't see a clean way to get out the line and column numbers out of the `Ast::Test`, or `Ast::Test#from` specifically - as I understand, the latter - translates to the starting position of the `test` keyword, measured by the position in the `input` char array, which is not directly translatable into a line and column numbers.

@gdotdesign Any ideas how to approach this?

The rest, that is extending js test objects and logging back their location, is pretty str8forward.

**Comment by gdotdesign** [comment]
We came across this before in LSP we need to find nodes from line/column:
https://github.com/mint-lang/mint/blob/master/src/lsp/protocol/text_document_position_params.cr#L31

And for the source mapping it needed exactly what is needed here:
https://github.com/mint-lang/mint/pull/356/files#diff-4dc5550733e54abb38f1208d097d747069797ee851c3075ebd43056f3ad32298R35

**Comment by Sija** [comment]
@gdotdesign Sweet, thanks for the hints! Do you think it might be better to move this functionality over to the `Ast` base class instead? In such a way this wouldn't need to be duplicated across the codebase.

**Comment by gdotdesign** [comment]
> @gdotdesign Sweet, thanks for the hints! Do you think it might be better to move this functionality over to the `Ast` base class instead? In such a way this wouldn't need to be duplicated across the codebase.

Yeah, good idea!
