### ISSUE TITLE
Provider.AnimationFrame does not provide DOMHighResTimeStamp argument

### ISSUE THREAD

**Issue by bbugh** [mint-lang/mint#445]
Hi! 👋 Wow, Mint has grown a lot since I last used it. The home page is beautiful and the documentation is excellent. Great work! 

While looking at built-in solutions for `requestAnimationFrame` I came across the `AnimationFrame` provider. Unfortunately, it does not provide components with the [`DOMHighResTimeStamp` argument](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#parameters) that `requestAnimationFrame` sends to the callbacks, which prevents deriving the elapsed time since the last animation frame. I was able to make my own provider to do this, but I thought this was worth reporting.

**Comment by gdotdesign** [comment]
> Hi! wave Wow, Mint has grown a lot since I last used it. The home page is beautiful and the documentation is excellent. Great work!

Thanks!



> While looking at built-in solutions for `requestAnimationFrame` I came across the `AnimationFrame` provider. Unfortunately, it does not provide components with the [`DOMHighResTimeStamp` argument](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#parameters) that `requestAnimationFrame` sends to the callbacks, which prevents deriving the elapsed time since the last animation frame. I was able to make my own provider to do this, but I thought this was worth reporting.

Yep we should add it, mind sharing your provider? :)

**Comment by bbugh** [comment]
Ah yeah, I thought I mentioned that I didn't post it because I don't know if it's right, but looks like I only thought about it and didn't actually say it. 😆 I don't use Crystal for anything else so didn't want to install it all (have you considered a Docker for contributions too?) - here's a diff of the code that reflects my custom provider:

```diff
diff --git a/core/source/AnimationFrame.mint b/core/source/AnimationFrame.mint
index 51efb52..01ad598 100644
--- a/core/source/AnimationFrame.mint
+++ b/core/source/AnimationFrame.mint
@@ -5,7 +5,7 @@ module AnimationFrame {
 
     id = AnimationFrame.request(() { Debug.log("Hello") })
   */
-  fun request (method : Function(a)) : Number {
+  fun request (method : Function(Number, Promise(Never, Void))) : Number {
     `requestAnimationFrame(#{method})`
   }
 
diff --git a/core/source/Provider/AnimationFrame.mint b/core/source/Provider/AnimationFrame.mint
index 6b102f5..869efc6 100644
--- a/core/source/Provider/AnimationFrame.mint
+++ b/core/source/Provider/AnimationFrame.mint
@@ -1,6 +1,6 @@
 /* Represents a subscription for `Provider.AnimationFrame` */
 record Provider.AnimationFrame.Subscription {
-  frames : Function(Promise(Never, Void))
+  frames : Function(Number, Promise(Never, Void))
 }
 
 /* A provider for the `requestAnimationFrame` API. */
@@ -9,10 +9,10 @@ provider Provider.AnimationFrame : Provider.AnimationFrame.Subscription {
   state id : Number = -1
 
   /* Call the subscribers. */
-  fun process : Promise(Never, Void) {
+  fun process (timestamp : Number) : Promise(Never, Void) {
     try {
       for (subscription of subscriptions) {
-        subscription.frames()
+        subscription.frames(timestamp)
       }
 
       next { id = AnimationFrame.request(process) }
```
