### ISSUE TITLE
Add asset path alias

### ISSUE THREAD

**Issue by Braayy** [mint-lang/mint#459]
I was thinking about the path aliases of other frameworks and because the components, store and etc are global in Mint, the only need for path alias is for the asset and svg directives.

So i did think about using `#assets` so the whole `../../../../assets/` thing are gone.

An example would be `@svg(#assets/icons/plus.svg)`

If that is a good idea, i would start coding it.

**Comment by Sija** [comment]
Do you mean path _prefix_?

**Comment by gdotdesign** [comment]
I think the right approach would be to use the root path `/` as the project root because you probably don't want to include something which is absolute to the file system.
