### ISSUE TITLE
LSP: Support for disabling snippets

### ISSUE THREAD

**Issue by TeddyDD** [mint-lang/mint#466]
My LSP client has snippet support disabled, but they still appear as suggestions in completion.

**Comment by gdotdesign** [comment]
Hi :wave: can you elaborate a bit?

- which client are you using? because the VSCode extension has it's own snippets which I'm not sure that can be disabled.
- how are you disabling snippets in your LSP client?
- what snippets you don't want to see?

**Comment by TeddyDD** [comment]
I'm using [kak-lsp](https://github.com/kak-lsp/kak-lsp). It has [option](gghttps://github.com/kak-lsp/kak-lsp) to disable snippets support.

I have it enabled, but I'm still getting placeholders in completed functions.

![screen-2021-06-18-104920](https://user-images.githubusercontent.com/4397533/122534514-e686ee00-d022-11eb-8fda-76ff0eb11b72.png)
![screen-2021-06-18-104939](https://user-images.githubusercontent.com/4397533/122534525-e8e94800-d022-11eb-8be7-57549895759d.png)

**Comment by gdotdesign** [comment]
Thanks for the information :pray: 

Are you still expecting completions? for example instead of:

```
Http.jsonBody(${1:body}, ${2:request})
```

it would be:

```
Http.jsonBody(body, request)
```

**Comment by TeddyDD** [comment]
With placeholders disabled, I'd expect only `Http.jsonBody(` to be present in the completion list, so I can type the args myself.
