### ISSUE TITLE
Can mint be installed on windows

### ISSUE THREAD

**Issue by drnkwati** [mint-lang/mint#47]
Hi
Are they any windows installers

**Comment by gdotdesign** [comment]
Hey, 

There is no windows installer, mint is built with Crystal https://crystal-lang.org which does not support windows yet.

I suggest that you try use the linux binary in Windows Subsystem for Linux
 https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by drnkwati** [comment]
Sounds hacky
