### ISSUE TITLE
Syntax error in "Header.mint" ????

### ISSUE THREAD

**Issue by jakesellis** [mint-lang/mint#474]
SYNTAX ERROR
The body of a case expression must end with a closing bracket.

I was looking for the bracket } but found Ui.NavItem::Html instead.

Here is the relevant code snippet:

/home/jakesellis/Development/MintPrjs/daylin/.mint/packages/mint-ui/source/Header.mint
153
154
155
156
157
158
159
160
161
            for (item of items) {
              case (item) {
                Ui.NavItem::Divider => <div::divider/>
                Ui.NavItem::Html content => content

                Ui.NavItem::Group iconBefore iconAfter label items =>
                  try {
                    key =
                      String.parameterize(label)

**Comment by gdotdesign** [comment]
Hi @jakesellis :wave: 

You are trying to use an incompatible version of Mint UI with your installed Mint, these are the compatible versions:

- mint `0.14.x` :arrow_right: mint-ui `3.0.0 <= v < 4.0.0`
- mint `0.13.x` :arrow_right: mint-ui `2.0.0 <= v < 3.0.0`
- mint `0.12.x` :arrow_right: mint-ui `0.0.0 <= v < 2.0.0`
