### ISSUE TITLE
Inline stlyes only emit the first style property

### ISSUE THREAD

**Issue by cie** [mint-lang/mint#483]
Hi! I'm new to Mint,  it's love at first sight.

It seems that inline styles are broken:

```html
<span style="color: red; font-size: 60px; ">
  "Hello"
</span>

<span style="font-size: 60px; color: red; ">
  "Hello"
</span>
```
![image](https://user-images.githubusercontent.com/243342/132154519-2af17c4c-2504-4703-bc49-5b1fff49348d.png)
[sandbox](https://sandbox.mint-lang.com/sandboxes/hA5aLl08s9Cfjg)

But I'll probably use styles with interpolations instead, so it's not important for me.

**Comment by gdotdesign** [comment]
It's a bug, the space which separates the properties causes this.

If removed, it works fine: https://sandbox.mint-lang.com/sandboxes/CpLd5V27W9PB3A

**Comment by cie** [comment]
Thanks!
