### ISSUE TITLE
Weird syntax error on undefined identifier

### ISSUE THREAD

**Issue by cie** [mint-lang/mint#487]
Hello,
This error message puzzled me.

```mint
enum Token {
  As
}

module Mod {
  const TOKENS = [
    {A, (s : String) { A }},
    {"a", (s : String) { Token::As }},
    {"a", (s : String) { As }}
  ]
}
```
`Line 9: The body of a record must end with a closing bracket.
I was looking for the bracket } but found "a", instead.`

The problem was that `As` is not defined, only `Token::As`. But the same error doesn't come for `A`, which is not defined either.

https://sandbox.mint-lang.com/sandboxes/zRGwYXyqzRL9HQ

**Comment by gdotdesign** [comment]
It seems this was fixed with `0.20.0`
![Image](https://github.com/user-attachments/assets/958c8c03-824b-4a07-b352-5b939446b43e)
