### ISSUE TITLE
Cannot pattern match nested enums

### ISSUE THREAD

**Issue by cie** [mint-lang/mint#489]
Hi,

I'd like to pattern match nested structures in a case statement: 
```
enum B {
  B1(Maybe(Number))
}

module Mod {
  fun fn(x : B) {
    case(x) {
      B::B1(Maybe::None) => "ok"
      B::B1(Maybe::Just(4)) => "ok"
      => "not ok"
    }
  }
}
```
It says:
> I was looking for the closing parenthesis ) of the destructuring of an enum but found Maybe::None) instead.

https://sandbox.mint-lang.com/sandboxes/tlzIzuhJeaZ5jw

**Comment by gdotdesign** [comment]
It's not possible yet, see #226

**Comment by cie** [comment]
Thanks! :)
