### ISSUE TITLE
Could not decode the documentation!

### ISSUE THREAD

**Issue by TeddyDD** [mint-lang/mint#490]
```
$ mint version 
# downloaded from wget --no-verbose -O mint https://mint-lang.s3-eu-west-1.amazonaws.com/mint-master-linux at Mon Sep 20 06:18:58 PM CEST 2021

Mint 0.15.0-devel

$ mint init foo && cd foo && mint docs
```

When I open localhost:3002 there is only "Could not decode the documentation!" error visible.

**Comment by richi0** [comment]
I have the same problem. I posted about this in discord a few days ago. That's what the console says:

`Uncaught (in promise) DOMException: Failed to execute 'respondWith' on 'FetchEvent': The event handler is already finished.
    at http://127.0.0.1:3002/service-worker.js:80:35`

I could not solve it so far.

**Comment by richi0** [comment]
I also found a similar issue from some months ago [issue](https://github.com/mint-lang/mint/issues/341)

**Comment by TeddyDD** [comment]
I see nothing in console except

```
Failed to add shortcut on window frame 0: SecurityError: Permission denied to access property "addEventListener" on cross-origin object
```

which probably is related to one of my browser add-ons.

I tried to clear cache/data/cookies, unregister service worker. It does not help.
