### ISSUE TITLE
pipe in tuple

### ISSUE THREAD

**Issue by cie** [mint-lang/mint#491]
Hi,
It seems the parser cannot parse a tuple starting with `{ x |>`
```
module Mod {
  const A = {x |> Number.toString}[0]
}
```
> I was expecting at least one field to update but found > instead.

https://sandbox.mint-lang.com/sandboxes/QqqsxUwmO01hxg

**Comment by Sija** [comment]
Workaround is to wrap the expression in `()`: `const A = { (x |> Number.toString) }`

**Comment by cie** [comment]
Thanks!
