### ISSUE TITLE
Mint compile and embedded program documentation

### ISSUE THREAD

**Issue by nozzlegear** [mint-lang/mint#496]
I can't seem to find any documentation about the `Mint.embed` function. Through some tinkering around, it looks like this is something that I'd like to use to render a Mint program inside part of my app without first converting the entire thing to Mint. 

I've found that if I use `mint compile` I can then load the JS file into my app and call `Mint.embed(targetElement)` to render Mint exactly where I want it. However, it seems when I do this the routing functionality is completely disabled; but if I use `mint build`, I don't get to decide which element the program is rendered into, and it just renders outside the rest of my app's existing navigation elements. 

I'm guessing because the `mint compile` isn't documented that this scenario may not be supported?

Edit: woops, I filed this issue and then checked which version of Mint I'm running. I'm somehow on Mint 0.15.0-devel which is not released. I'm not even sure how I got that version. I'll leave this open for confirmation but I'll assume that `mint compile` might be an upcoming feature and hasn't been documented yet.

**Comment by Sija** [comment]
Related: #144

**Comment by nozzlegear** [comment]
Thanks! That makes sense and I can work around it knowing it's not supported. I couldn't find any documentation about the compile process so I didn't know if routes weren't supposed to work or if I'd broken something.
