### ISSUE TITLE
Deprecation error in the coming Crystal 1.2.0

### ISSUE THREAD

**Issue by beta-ziliani** [mint-lang/mint#502]
For security reasons we decided to [deprecate](https://github.com/crystal-lang/crystal/pull/11248) the use of `URI.encode` in favor of more precise methods, in order to avoid [security pitfalls](https://github.com/crystal-lang/crystal/issues/10603). Since Mint is compiled to error on warnings, that means it [fails to compile](https://github.com/crystal-lang/test-ecosystem/runs/3847459889?check_suite_focus=true) on nightly. The fix is to use the appropriate new methods instead (like `URI.encode_path` or `URI.encode_www_form`, depending on the use case). If you want to keep compatibility with older versions of the lib, you can still use a macro to select the right method ([example](https://github.com/crystal-lang/crystal/blob/dfd3e5f0a797a48b05a4916ff7f7f637bd3c9e14/src/indexable/mutable.cr#L145)).

**Comment by Sija** [comment]
Fixed in 66f3ea9acfd9e987ab55ac5a79e579e13894ad40
