### ISSUE TITLE
[LSP] Include CSS and HTML completions

### ISSUE THREAD

**Issue by siduck** [mint-lang/mint#511]
Hi there! been learning mint for a while now and the lsp works very fast and lightweight but I dont get any css and html completions. I could make html , css lsps run on mint filetype tho but those lsps are heavy on my low end machine with just 4gb ram :disappointed: . I had been working with react recently but while working with react projects my ram almost gets full with all those heavy node stuffs running in the background and Im no longer able to type anything. I found mint which had way lighter lsps and formatters so tried checking it but I miss css , html completions

It would be great to add html , css completions functionalities in mint lsp! 

something like these : 

![image](https://user-images.githubusercontent.com/59060246/141437148-8d6df8b8-1b72-485c-b251-96345a3ab37f.png)

Css properties and values: 

![image](https://user-images.githubusercontent.com/59060246/141437208-daba0ddd-c703-44f9-970a-67805de494c0.png)
![image](https://user-images.githubusercontent.com/59060246/141437294-818faa2c-9f75-4219-aefa-f0c3760a740c.png)

**Comment by Sija** [comment]
I feel your pain, adding those to the mint lsp though seems out of scope IMO.

**Comment by gdotdesign** [comment]
> I feel your pain, adding those to the mint lsp though seems out of scope IMO.

Not necessarily, we already have most of the CSS properties in the repository: https://github.com/mint-lang/mint/blob/master/src/assets/css_properties, we can display completions for them only if the cursor is inside a style block.

Adding the values is another matter but not impossible, adding CSS properties and basic HTML tags is a good first step IMO.

**Comment by Sija** [comment]
> Not necessarily, we already have most of the CSS properties in the repository: https://github.com/mint-lang/mint/blob/master/src/assets/css_properties, we can display completions for them only if the cursor is inside a style block.

That's true, but there's more to completions than the property names. Adding values and the rest would be essentially duplicating LSP server for HTML/CSS - which could be a good topic for a separate, Crystal-based LSP for those languages.

**Comment by siduck** [comment]
> > Not necessarily, we already have most of the CSS properties in the repository: https://github.com/mint-lang/mint/blob/master/src/assets/css_properties, we can display completions for them only if the cursor is inside a style block.
> 
> That's true, but there's more to completions than the property names. Adding values and the rest would be essentially duplicating LSP server for HTML/CSS - which could be a good topic for a separate, Crystal-based LSP for those languages.

I think it would still be important since anyone working with mint would obviously using html, css stuff in it and not getting those completions might get frustrating
