### ISSUE TITLE
Compiler doesn't accept interpolation in CSS tag property selectors

### ISSUE THREAD

**Issue by ryanprior** [mint-lang/mint#515]
### Problem statement

The Mint compiler accepts CSS tag property selector like `[data-role="example"]`, but it will not permit interpolation of values into them.

Here's a sandbox illustrating the issue: https://sandbox.mint-lang.com/sandboxes/CALMUn5tVpSNaw

**Comment by gdotdesign** [comment]
It's not possible, unfortunately. Selectors are inherently static, and they compile into static CSS, while variables with interpolation can compile down to CSS variables.

**Comment by ryanprior** [comment]
Okay, thank you!
