### ISSUE TITLE
Dealing with boilerplate when writing Inline Javascript

### ISSUE THREAD

**Issue by frnco** [mint-lang/mint#523]
After working on slightly more complex modules dealing with custom types, and especially after working on some ideas for the `Time` module, one problem that I hadn't previously encountered but became recurrent is dealing with boilerplate Javascript. One specific example that makes it quite obvious is when I started working on a way to implement Javascript's 'Date`'s `set` functions, first I created an `enum` to keep track of the different possible units of time, hoping a simple `match` could be used to branch. However, the `set` functions are OO, not functional, and instead of returning the modified time they change the value in-place, thus the inline JavaScript needs to store `Time` in a variable, then modify it using the `set` function, and since the purpose is to increment or decrement the value I also need to use the corresponding `get` function from Javascript's `Date` module... Well this should be sufficient to understand how it works, so here's the code:

```
/* Shifts the time passed forward if direction is true, backward otherwise, and returns the result  */
fun shift(direction : Bool, delta : Time.Delta, time : Time) : Time {
  case (delta) {
    Time.Delta::Milliseconds(amount) => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCMilliseconds(time.getUTCMilliseconds() + offset); return time;})()`
    Time.Delta::Seconds(amount)      => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCSeconds(     time.getUTCSeconds() +      offset); return time;})()`
    Time.Delta::Minutes(amount)      => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCMinutes(     time.getUTCMinutes() +      offset); return time;})()`
    Time.Delta::Hours(amount)        => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCHours(       time.getUTCHours() +        offset); return time;})()`
    Time.Delta::Days(amount)         => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCDate(        time.getUTCDate() +         offset); return time;})()`
    Time.Delta::Weeks(amount)        => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 7 : -7)); time.setUTCDate(        time.getUTCDate() +         offset); return time;})()`
    Time.Delta::Months(amount)       => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCMonth(       time.getUTCMonth() +        offset); return time;})()`
    Time.Delta::Years(amount)        => `(() => { var time = #{time}; var offset = (#{amount} * (#{direction} ? 1 : -1)); time.setUTCFullYear(    time.getUTCFullYear() +     offset); return time;})()`
  }
}
```

Putting it in simple bullet-points, every branch needs to:
1. Store `Time` in a variable (`var time = #{time};`) - identical code in all branches;
2. Calculate an offset, only code dealing with `week` differs here since it uses the same code as `days`, however that could be changed so all branches were the same;
3. Getting the current value that will be changed, this is different for each branch (`time.getUTCHours`/`time.getUTCMinutes`/etc.)
4. Adding the offset to the current value that was fetched (Same now, but could be different to deal with `week`s);
5. Setting the current value that will be changed, this is also different for each branch (`time.setUTCHours`/`time.setUTCMinutes`/etc, to use the same example as above);
6. Return `said variable after changing it (`return time;`) - identical code in all branches;

Ideally, I'd like to be able to it in a simpler way, such as:
````
/* Shifts the time passed according to the Delta provided */
fun shiftBranching(delta : Time.Delta) : String {
  case (delta) {
    Time.Delta::Milliseconds(amount) => "time.setUTCMilliseconds(time.getUTCMilliseconds() + offset)"
    Time.Delta::Seconds(amount)      => "time.setUTCSeconds(     time.getUTCSeconds() +      offset)"
    Time.Delta::Minutes(amount)      => "time.setUTCMinutes(     time.getUTCMinutes() +      offset)"
    Time.Delta::Hours(amount)        => "time.setUTCHours(       time.getUTCHours() +        offset)"
    Time.Delta::Days(amount)         => "time.setUTCDate(        time.getUTCDate() +         offset)"
    Time.Delta::Weeks(amount)        => "time.setUTCDate(        time.getUTCDate() +   (7 * offset))"
    Time.Delta::Months(amount)       => "time.setUTCMonth(       time.getUTCMonth() +        offset)"
    Time.Delta::Years(amount)        => "time.setUTCFullYear(    time.getUTCFullYear() +     offset)"
  }
}

/* Shifts the time passed forward if direction is true, backward otherwise, and returns the result  */
fun shift(direction : Bool, delta : Time.Delta, time : Time) : Time {
  `(() => {
    var time = #{time};
    var offset = (#{amount} * (#{direction} ? 1 : -1));
    eval(#{shiftBranching(delta)})
  })()`
}
```

But everybody hates stuff `eval`, and I'm not any different. However, perhaps there is another way I'm failing to realize, or if there isn't, perhaps some way to do this kind of thing could be added to Mint.

The point is to have a simpler way to combine segments of javascript code from multiple functions, so that boilerplate can be refactored. That can be done by having Templates, by using `eval`, really there are so many ways to do that that the hardest part is deciding which one to use. Mint doesn't need all of them, but it would be nice to have at least one option to deal with this.

**Comment by gdotdesign** [comment]
As inline JavaScript is well inline :sweat_smile: you can do something like this:

```
/* Shifts the time passed forward if direction is true, backward otherwise, and returns the result  */
fun shift(direction : Bool, delta : Time.Delta, time : Time) : Time {
  try {
    // Declare cloned version of time in a JavaScript variable.
    `const time = new Date(+#{time});`

    // Helper function to calculate the offset.
    offset = (amount : Number) {
      if (direction) {
        amount * 1
      } else {
        amount * -1
      }
    }

    // Set the the values, calculate the offset using the helper function and interpolation.
    case (delta) {
      Time.Delta::Milliseconds(amount) => `time.setUTCMilliseconds(time.getUTCMilliseconds() + #{offset(amount)})`
      Time.Delta::Seconds(amount)      => `time.setUTCSeconds(     time.getUTCSeconds() +      #{offset(amount))`
      Time.Delta::Minutes(amount)      => `time.setUTCMinutes(     time.getUTCMinutes() +      #{offset(amount))`
      Time.Delta::Hours(amount)        => `time.setUTCHours(       time.getUTCHours() +        #{offset(amount))`
      Time.Delta::Days(amount)         => `time.setUTCDate(        time.getUTCDate() +         #{offset(amount))`
      Time.Delta::Weeks(amount)        => `time.setUTCDate(        time.getUTCDate() +   (7 * #{offset(amount)))`
      Time.Delta::Months(amount)       => `time.setUTCMonth(       time.getUTCMonth() +        #{offset(amount))`
      Time.Delta::Years(amount)        => `time.setUTCFullYear(    time.getUTCFullYear() +     #{offset(amount))`
    }

    // Return the time.
    `time`
  }
}
```

_I haven't actually tested it, but it should work._

Alternatively you can put the `case` in an interpolation:

```
/* Shifts the time passed forward if direction is true, backward otherwise, and returns the result  */
fun shift(direction : Bool, delta : Time.Delta, time : Time) : Time {
  `(() => {
    const time = new Date(+#{time});`
    const offset = (#{amount} * (#{direction} ? 1 : -1));
    
    #{
      case (delta) {
        Time.Delta::Milliseconds(amount) => `time.setUTCMilliseconds(time.getUTCMilliseconds() + offset)`
        Time.Delta::Seconds(amount)      => `time.setUTCSeconds(     time.getUTCSeconds() +      offset)`
        Time.Delta::Minutes(amount)      => `time.setUTCMinutes(     time.getUTCMinutes() +      offset)`
        Time.Delta::Hours(amount)        => `time.setUTCHours(       time.getUTCHours() +        offset)`
        Time.Delta::Days(amount)         => `time.setUTCDate(        time.getUTCDate() +         offset)`
        Time.Delta::Weeks(amount)        => `time.setUTCDate(        time.getUTCDate() +   (7 * offset))`
        Time.Delta::Months(amount)       => `time.setUTCMonth(       time.getUTCMonth() +        offset)`
        Time.Delta::Years(amount)        => `time.setUTCFullYear(    time.getUTCFullYear() +     offset)`
      }
    }

    return time;
  })()`
}
```
Interpolations and inline JavaScript can be nested infinitely.

**Comment by frnco** [comment]
> Interpolations and inline JavaScript can be nested infinitely. _Edit: The second example._

That's actually quite a nice surprise. The syntax, however, doesn't look too nice, especially in the second example. I hadn't considered using `try` though, usually I limit multiple statements to functions that return `Promise`s and I tend to prefer `sequence`/ `parallel`, but this works pretty well for what I had in mind.

I do try to avoid using `const` for variables that are mutable, maybe because I got used to Rust, but other than that this seems like a really nice way to deal with this. As my luck would have it, however, the examples didn't work, mint keeps complaining saying `An internal error occurred while executing a test: Uncaught SyntaxError: Unexpected token`, followed by whatever I have in the inlined Javascript (`var`, `const`, even parenthesis and `;`...).

That, however, made me realize we could definitely use Tuple Destructuring in the definition of function arguments. So instead of something like:
```
fun numberWithUnit (tuple : Tuple(Number,SomeUnitEnumOrStringOrWhatever)) : Something {
   [...]
} where {
  {number,unit} = tuple
}
```
we could write something like
```
fun numberWithUnit ({number,unit} : Tuple(Number,SomeUnitEnumOrStringOrWhatever)) : Something {
   [...]
}
```
If you do know about something related to that, do tell.


As for nesting inline javascript, that didn't work, the second version tells me `lo` is not a function, I can't find the compiled Javascript to confirm but I'm inclined to believe `lo` refers to the inlined javascript function (i.e. `(() => {})()`), which Mint is probably failing to compile because of the `#{case}`, maybe because it inserts more JavaScript, maybe something else.

**Comment by gdotdesign** [comment]
> I do try to avoid using `const` for variables that are mutable, maybe because I got used to Rust, but other than that this seems like a really nice way to deal with this. As my luck would have it, however, the examples didn't work, mint keeps complaining saying `An internal error occurred while executing a test: Uncaught SyntaxError: Unexpected token`, followed by whatever I have in the inlined Javascript (`var`, `const`, even parenthesis and `;`...).

I left a backtick at the end of the line, that's why it didn't compile. I've put together a sandbox where it works https://sandbox.mint-lang.com/sandboxes/ebAXP5g3Sj2wUA

> you do know about something related to that, do tell.

There is no feature like that (yet).

**Comment by frnco** [comment]
> There is no feature like that (yet).

I imagined it would be so. I'll take a look at how it might be implemented and after I figure out how I might do it I'll open an issue to check with you guys whether it's good enough to submit a PR.

As for the code, I didn't copy-paste so the extra backtick was not the problem in my case. After investigating a bit more, which was made a lot easier by having your sandbox as a reference, I figured out the main issue in my case was that I was including `;` in the end of the single-line-inline-javascript called by the `case`, and apparently, when inlining a single javascript statements (As opposed to a `()()` function), putting `;` at the end of the javascript statement throws the error `❗ An internal error occurred while executing a test: Uncaught SyntaxError: Unexpected token ';'`.

I'm putting the full error message here again to make it more likely that this will be found by anyone with the same problem, but this probably deserves being included in the documentation about inline javascript.

The syntax still feels a bit with all the nesting and such, and we probably could use some syntax that made this more clear, I thought about a function that returns a Javascript statement but doesn't run it, instead running that Javascript in the context where the function was called, maybe it could be something like:

```
fun runJavascriptInCallerContext(useAlert : Bool) : JavascriptSomething {
  if (useAlert) {
    #`alert(message)`
  } else {
    #`console.log(message)`
  }
}
fun putMessage(message: String, useAlert : Bool) : Promise(Never,Void) {
  `
  (() => {
    message = #{message};
    #{runJavascriptInCallerContext(useAlert)}
  })()
  `
}
fun loginError : Promise(Never,Void) {
  sequence {
    putMessage("There was an error logging in, please check whatever", true);
    putMessage("Message with Debug data, which is sent to the developer tools console", false);
  }
}
```

This example is very simplistic so it wouldn't even justify using this feature but it shows how it might work, and how it helps refactoring code in separate functions. Another solution I considered was to have some way of running some Javascript code prior to some function, either through something similar to Rails's `before_` and `after_` `filter`s/`action`s, or through something like Mint's `componentDidMount` lifecycle function, only in this case it would just contain some javascript that would be accessible to any javascript code inlined in the same module or something. This was actually the first thing I considered, then I had the `before`/`after` idea which looked better, and in the latest iteration I started leaning towards allowing functions not only to execute inline Javascript code in their context when called, but also to execute inline Javascript code in the context of the caller, or, maybe even better, work as a templating kind of thing, resulting in something equivalent to replacing the `#{functionCall()}` with whatever JavaScript code it contained. That would allow stuff like
```
fun notify(useAlert : Bool) : Javascript {
  if (useAlert) {
      #`alert(message)`;
  } else {
      #`console.log(message)`;
  }
}
/* Returning an array for the example since ; throws errors.  */
/* This is the main point of making it work in a template-like-way. */
*/ If it waits to run all the JS code at once, this works. Otherwise it'd either be impossible or */
/* it'd have to be written as something like #`#{notify(true)}` which is less than ideal.   */
/* Notice how this sets the message which is later used by modify, while at the same time */
/* relying on someJSLoggingFunction which has been defined in processError. */
fun errorRoutine(error : String) : Array(Javascript) {
  [
    #`var message = #{error}`,
    notify(true),
    #`someJSLoggingFunction(error)`,
    #`console.log("Error encountered, please check the logs.")`
  ]
}
fun processError(error : SomeKindOfError) : Promise(Never,Void) {
  `
    (() => {
      const someJSLoggingFunction = (errorStr) => {
        doSomethingHete();
      }
      #{
        for (statement of errorRoutine(error |> SomeError.asString) ) {
          statement /* Or Maybe something like Javascript.include(statement)? */
        }
      }
    })()
  `
}
fun something : Promise(Never,Void) {
  try {
    ...
  } catch SomeKindOfError => error {
    error
    |> processError
  }
```

Again, the example doesn't do anything that justifies the level of complexity, but it's sufficient to show some possible benefits of being able to manipulate inline JS as data, which allows for more complex interactions since you may split your JS across many functions and still run everything at once, all in the same context. I'm strongly against using `this` in JavaScript so I'll just mention that this would be pretty helpful for anyone who uses it.

I'll keep looking for how this could be improved, thanks again for the help @gdotdesign, if you have any ideas on how to improve the syntax, or even better, on ways to make it possible to run arbitrary JavaScript from multiple functions in the same context, please do share.

But this issue is about the JS Boilerplate itself, and there's a sandbox with a working example of how it can be dealt with. Sure, it may be a good idea to improve it but that's beside the point of this issue, so I'll be closing this. If I figure out some reasonable way to improve on the syntax then I'll open another issue regarding that.
