### ISSUE TITLE
The name is overused, you should choose a more unique one

### ISSUE THREAD

**Issue by ahungry** [mint-lang/mint#53]
We already have Mint (financial software) and Mint (Linux distro) - this language should get a more unique name.

**Comment by HorizonShadow** [comment]
How about something like "mint-lang"?

**Comment by kingsleyh** [comment]
I like Mint personally - even if other things share the name.

**Comment by jakehamilton** [comment]
I'll throw my opinion in the ring: I like Mint. The only other thing with the same name that came to mind was the linux distro and since that's so far removed from this project I don't think it's an issue.

**Comment by gdotdesign** [comment]
I have thought about the name for a long time, there are a lot of factors involved:

- I want it to convey that the language is new, light and fresh
- it has to be 2 to 4 characters long so it could be used as a file extension
- it should be catchy so people would notice it
- it should accommodate a good brand which is different from competitors (in color and feel)
- it should not be the same or similar to existing (mostly popular) programming languages 

It is really hard to find an unused name matching those requirements. 

The only thing people will confuse Mint is the linux distro and I think we can live with that.

**Comment by gdotdesign** [comment]
Closing, added this question to the README.

**Comment by thoran** [comment]
Could have combined #53 and #55 and called it Fun. It's a bit late now though!

**Comment by warrenstephens** [comment]
You should call it "nojs" -- pronounced "noise".
