### ISSUE TITLE
Development server doesn't work in WSL

### ISSUE THREAD

**Issue by HorizonShadow** [mint-lang/mint#54]
Running `mint start`:

```
josh@DESKTOP-D449P1P:~/dev/test$ mint start
Mint - Running the development server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚙ Ensuring dependencies... 4.017ms
⚙ Compiling... 410.217ms
```

```
C:\Users\horiz>netstat -an | grep "3000"
  TCP    127.0.0.1:63919        127.0.0.1:3000         SYN_SENT
```

Compare this to running ruby's Webrick on localhost:4567

```
C:\Users\horiz>netstat -an | grep "4567"
  TCP    127.0.0.1:4567         0.0.0.0:0              LISTENING
  TCP    [::1]:4567             [::]:0                 LISTENING
```

I mentioned in gitter that ruby's `thin` server had the same behavior, but I just tried it and that appear to have been fixed, however I can't find any reference to what explicitly fixed it.

**Comment by gdotdesign** [comment]
I found the issue, the server checks if the port is open to provide a nice error message here: https://github.com/mint-lang/mint/blob/master/src/utils/server.cr#L16 but for some reason this hangs on wsl.

It's fixed on master https://github.com/mint-lang/mint/commit/565fd58eabb889788d0be1b980cedc1c78a7c837 should work using the daily build.
