### ISSUE TITLE
`mint format some_file.mint` should return code 0 if no syntax error regardless if `some_file.mint` if changed.

### ISSUE THREAD

**Issue by zw963** [mint-lang/mint#548]
Please check following WIP discuss.

https://github.com/lassik/emacs-format-all-the-code/issues/198

Also following PR:

https://github.com/lassik/emacs-format-all-the-code/pull/200#issuecomment-1172305274

**Comment by lassik** [comment]
Sorry about the false alarm.

> The `format` only returns `1` if there is an error while formatting, this for example returns `0` for valid input:

That is The Right Thing To Do (TM).

```
$ echo '{}' >mint.json

$ echo 'module X {const A = ""}' >example.mint

$ mint format --stdin <example.mint >example2.mint; echo $?
0

$ mint format --stdin <example2.mint >/dev/null; echo $?
0
```

The above is exactly what we need.

**Comment by gdotdesign** [comment]
:+1: Can I close this issue then?

**Comment by zw963** [comment]
> I'm not sure what changes are requested here.

Okay, thanks for reply, in fact, the ``--stdin`` is really what we want i think.

Though, i don't understood why `mint format some_file.mint` will return 1 when some_file.mint
content get changes. in the purpose is used in CI, should we use like `mint format --check some_file.mint` instead?


> If you like to have formatting, I recommend using the mint language server itself, it has a command for formatting code and also format files when saved.

What you said is LSP server?

**Comment by lassik** [comment]
> Though, i don't understood why `mint format some_file.mint` will return 1 when some_file.mint
> content get changes.

That's right - I can reproduce this behavior. It seems different from the `--stdin` behavior.

**Comment by gdotdesign** [comment]
Yep that's a bug, reopening the issue then :)
