### ISSUE TITLE
comment with // not work?

### ISSUE THREAD

**Issue by zw963** [mint-lang/mint#550]
Following code sample come from https://github.com/mint-lang/mint-realworld project.

I try to comment the resetStores in following code use `// resetStores()`.

 But get following error (see screenshot)

```mint
  fun setUser (user : User) : Promise(Never, Void) {
    next { user = UserStatus::LoggedIn(user) }
  }

  fun logout : Promise(Never, Void) {
    sequence {
      Storage.Local.remove("user")

      // resetStores()

      next { user = UserStatus::LoggedOut }

      Window.navigate("/")
    } catch Storage.Error => error {
      Promise.never()
    }
  }
```

![image](https://user-images.githubusercontent.com/549126/190099663-de71d015-90fe-4f88-965a-878b6c2e4724.png)

If change above comment  to `/* resetStores() */`, it works as expected.

**Comment by gdotdesign** [comment]
With the syntax changes this exact code is no longer possible. I've tried to reproduce it but couldn't.

Feel free to reopen this if someone runs into it in newer versions (> 0.17.0).
