### ISSUE TITLE
Docker image support for arm64 platform

### ISSUE THREAD

**Issue by ivangsm** [mint-lang/mint#554]
Recently, I move my entire server infrastructure to arm64 servers, and I am looking for a replacement for Elm due to the poor support to this architecture. I'm trying mint and is so cool, but when I tried to test your docker image, I see that you only release a Linux/amd64 image.

As far as I know, all the dependencies to build and run mint works fine under arm64, I already tested to build the docker image under my server and under my M1 mac.

Is there any chance to release the image for both architectures?

I earnestly await your answer, thank you very much.

**Comment by gdotdesign** [comment]
Hi @ivangsm 

I don't have access to an M1 mac and GitHub actions still don't have runners for M1 mac (https://github.com/actions/runner-images/issues/2187) so I'm not sure how we can build docker images for M1. 

Overall I would be happy to offer docker images for M1 but I don't know how to do that :) If you have any resources on it It would be helpful, or you are welcome to can create a PR :)

**Comment by ivangsm** [comment]
@gdotdesign Thanks for the answer, sorry, maybe I didn't explain myself well.

I am not looking for an image for M1, but for linux/arm64, since your Dockerfile is fully compatible with this architecture, I already tested compiling it on my Mac M1 which uses this architecture as well as on my arm server.

I created a pipeline on GitHub actions, which compile and publish for both architectures and everything worked correctly, you can find the images created on https://ghcr.io/ivangsm/mint and the pipeline on my fork possibly tomorrow I will do a PR.

Although I can already work and deploy with my image, it would be nice if the official image also  adds support for that architecture.

**Comment by gdotdesign** [comment]
Ah, I understand now thanks :pray: 

We will probably migrate to GitHub Packages instead of Docker Hub so the workflow file you have will be perfect! :smile:
