### ISSUE TITLE
Allow React Fragments

### ISSUE THREAD

**Issue by d3dc** [mint-lang/mint#58]
It doesn't look like its possible to write:
```
<>
</>
```
or even
```
<React.Fragment>
</React.Fragment>
```

**Comment by gdotdesign** [comment]
Thank you for creating this issue! I am panning to add it but did not get around to it yet. 

If anyone wants to pick this issue up here are some requirements:
- [ ] It's name should be `HtmlFragment`
- [ ] The syntax should be an element without tagname which can only have the `key` attribute
      `<key=""></>`
- [ ] It should be part of the `HtmlContent` alias
- [ ] The type checker should check the `key` property as `String`
