### ISSUE TITLE
Tests for `src/messages`

### ISSUE THREAD

**Issue by jansul** [mint-lang/mint#600]
Following on from https://github.com/mint-lang/mint/pull/599. 

There have been a few times where it would have been useful to have tests for the error messages generated by the files in `src/messages` (at least for me :sweat_smile:, there was a few `#<Mint::Ast::TypeId...`'s being outputted [during that change](https://github.com/mint-lang/mint/pull/592#issuecomment-1529571681) and I'm not sure I got them all!)

As most of the exceptions covered by the messages already have test cases (see `spec/parsers/*`and `spec/type_checking/*`), it should be possible to generate these tests with hopefully not too much effort.

My thought was was to have them similar to some of the other tests:

```
enum A {
  B
  C
  /* Comment for D enum option */
  D
}

component Main {
  fun render : String {
    case (A::B) {
      A::B => "a"
      A::C => "c"
    }
  }
}
--------------------------------------------------------------------------------
░ TYPE ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

Not all possibilities of a case expression are covered.

To cover all remaining possibilities create branches for the following options:

  • A::D

Here is the relevant code snippet:

┌──┬ ./spec/messages/case_enum_not_covered:10:5 ───────────────────────────────┐
│ 6│ }                                                                         │
│ 7│                                                                           │
│ 8│ component Main {                                                          │
│ 9│   fun render : String {                                                   │
│10│     case (A::B) {                                                         │
│11│       A::B => "a"                                                         │
│12│       A::C => "c"                                                         │
│13│     }                                                                     │
│14│   }                                                                       │
│15│ }                                                                         │
└──┴───────────────────────────────────────────────────────────────────────────┘
```

There may be a better way of testing them, or it may not be worth testing them directly at all. Thoughts? :smiley:

**Comment by Sija** [comment]
I'd test just the behavior part and not the renderer.

**Comment by Sija** [comment]
Maybe it would be enough to write the set of assertions for the parts of the `message` dsl, sth like `assert_title`, `assert_block`, `assert_list`, etc.

**Comment by jansul** [comment]
> Maybe it would be enough to write the set of assertions for the parts of the `message` dsl, sth like `assert_title`, `assert_block`, `assert_list`, etc.

I think the only issue with this would be that, as with the recent error, some of the formatting is done [outside of the messages/renderers](https://github.com/mint-lang/mint/blob/master/src/type_checkers/case.cr#LL80C1-L83C15).

If that logic was moved inside the message methods (i.e. if it receives an array of enum options, it should render a certain way) likely just testing those methods would be enough?

I am a fan of testing the "surface area" of an application which is why I do like the approach from the original comment. But I also understand not wanting to add 300-400 files of rendered error messages to the project 😅

**Comment by gdotdesign** [comment]
Something like this was an issue before where the errors were erroring out :joy: because of missing things and such, and because of that I added these to the type checking specs: https://github.com/mint-lang/mint/blob/master/spec/type_checking_spec.cr#L45 which just checks if the errors can be rendered OK.

I like the enthusiasm here :slightly_smiling_face: I'm planning to refactor the error system in the near future and I have a somewhat working solution, but even that doesn't fix this specific problem.

I like integration tests like that you presented, so if you want to add some of these tests you are most welcome :+1: 

------------

I remembered that there is https://github.com/elm/error-message-catalog (long abandoned) which is similar.

**Comment by gdotdesign** [comment]
Maybe at first pass we can add some checks here https://github.com/mint-lang/mint/blob/master/spec/type_checking_spec.cr#L45 that fails if the output has `#<Mint::` in it, WDYT?

**Comment by jansul** [comment]
> I'm planning to refactor the error system in the near future and I have a somewhat working solution, but even that doesn't fix this specific problem.

Possibly worth waiting until after this refactor before adding these tests, if it's likely the output would change?

> Maybe at first pass we can add some checks here https://github.com/mint-lang/mint/blob/master/spec/type_checking_spec.cr#L45 that fails if the output has `#<Mint::` in it, WDYT?

I did try this on a local branch just to check if I had introduced any errors, and luckily it didn't seem to catch anything 😄 

> I remembered that there is https://github.com/elm/error-message-catalog (long abandoned) which is similar.

I assume the current Mint error messages were inspired [by Elm's ones](https://elm-lang.org/news/compiler-errors-for-humans)? 

Would be nice to have something similar to that repository (although just using the code samples from the existing tests as mentioned above would be a good start) for some of the more confusing error messages you can get. e.g. The recent one https://github.com/mint-lang/mint-tutorial/issues/8 should probably be complaing about the constant starting with a `2` rather than a space 😅

**Comment by gdotdesign** [comment]
> Possibly worth waiting until after this refactor before adding these tests, if it's likely the output would change?

Yes, it would probably change a bit (not much though).

> I assume the current Mint error messages were inspired [by Elm's ones](https://elm-lang.org/news/compiler-errors-for-humans)?

Yes, Mint is inspired by (or more precisely came from the frustration of) Elm.

> Would be nice to have something similar to that repository (although just using the code samples from the existing tests as mentioned above would be a good start) for some of the more confusing error messages you can get. e.g. The recent one [mint-lang/mint-tutorial#8](https://github.com/mint-lang/mint-tutorial/issues/8) should probably be complaing about the constant starting with a `2` rather than a space :sweat_smile:

Well, it would be difficult to maintain manually :slightly_smiling_face:

**Comment by gdotdesign** [comment]
With the refactors merged, there are no tests for errors: https://github.com/mint-lang/mint/tree/master/spec/errors around ~300 which I went through and updated :slightly_smiling_face:
