### ISSUE TITLE
@asset is different in Mac and Ubuntu systems

### ISSUE THREAD

**Issue by wyasher** [mint-lang/mint#622]
This module defines some image resources
```
module Icons {
  const PHONE = @asset(../../../assets/icons/phone.png)
  const ERROR_CLOSE = @asset(../../../assets/icons/error_close.png)
  const ERROR_REFRESH = @asset(../../../assets/icons/error_refresh.png)
  const EYES_CLOSE = @asset(../../../assets/icons/eyes_close.png)
  const EYES_DISABLE = @asset(../../../assets/icons/eyes_disable.png)
  const PASSWORD = @asset(../../../assets/icons/password.png)
  const BACK = @asset(../../../assets/icons/back.png)
  const CLOSE = @asset(../../../assets/icons/close.png)
  const SMS_CODE = @asset(../../../assets/icons/sms_code.png)
  const REFRESH = @asset(../../../assets/icons/refresh.png)
  const SUCCESS = @asset(../../../assets/icons/success.png)
  const WARNING = @asset(../../../assets/icons/warning.png)
  const SEND = @asset(../../../assets/icons/send.png)
  const ICON = @asset(../../../assets/icons/icon.png)
}
```
I accidentally defined the path where these icons are stored /assets/Icons/,not /assets/icons/.
But unexpectedly, it can run on the mac. It seems to ignore uppercase and lowercase letters. But when I packed on the ubuntu system, the problem occurred, saying that these files could not be found

**Comment by gdotdesign** [comment]
I think it's the behavior of the operating system. MacOS is not case-sensitive by default https://discussions.apple.com/thread/251191099 while Linux usually is https://superuser.com/questions/431342/linux-both-case-sensitive-and-case-insensitive-and-always-inconvenient

**Comment by wyasher** [comment]
> I think it's the behavior of the operating system. MacOS is not case-sensitive by default https://discussions.apple.com/thread/251191099 while Linux usually is https://superuser.com/questions/431342/linux-both-case-sensitive-and-case-insensitive-and-always-inconvenient

Thank you
