### ISSUE TITLE
Compiler allows strange things regarding `const`

### ISSUE THREAD

**Issue by farism** [mint-lang/mint#638]
This is allowed for some reason

```mint
component Main {
  const A = "a"

  fun render : Html {
    let a =
      A("A is a String constant, but calling it like a function compiles")

    <div>
      <{ a }>
    </div>
  }
}
```

Interestingly, if you try to call with no arguments like `let a = A()` then the formatter will remove the parenthesis. It's seems like it just ignores everything after the variable.

So something like this won't compile

```mint
component Main {
  const A = () { "a" }

  fun render : Html {
    let a = A()

    <div>
      <{ a }>
    </div>
  }
}
```

Because you get a type error. Although I'm not sure if const functions should even be allowed by the compiler?

```mint
░ TYPE ERROR ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

A child node of an element or component has an invalid type. 

I was expecting one of the following types: 

  Html, String, Array(String), Array(Html)

Instead it is: 

  Function(String)
```

**Comment by gdotdesign** [comment]
This is already fixed in the `refators` branch and will be in the 0.20.0 release.
