### ISSUE TITLE
`mint format` issues

### ISSUE THREAD

**Issue by farism** [mint-lang/mint#640]
Running `mint format` today will not work if there are type errors anywhere in the project.

`mint format` should

- Be able to run independently from the typechecker.
- Only care about syntax. If a file can be parsed it can be formatted.
- Only care about one file at a time. Syntax errors elsewhere in the project should not prevent an individual file being formatted.

**Comment by gdotdesign** [comment]
The issues with `mint format` command is that it if it can't find a `mint.json` file, then it errors out, also it doesn't type check anything.
