### ISSUE TITLE
Allow `fun` inside of `suite` blocks

### ISSUE THREAD

**Issue by farism** [mint-lang/mint#645]
It would be great for testing if we could write helper functions inside of `suite` and `test` blocks.

```mint
suite "Tests" {
  fun helperHere() {
  }

  test "it does something" {
    fun orHere() {
    }
  }
}
```

A fairly easy workaround is creating a `module` to contain your test helper functions, but that would seem largely unnecessary in most cases if we had direct `fun` support.

**Comment by gdotdesign** [comment]
It's possible to add functions to `suite` but not for `test` because tests are expression blocks, so there it's possible to use anonymous functions instead:

```
test "it should work" {
  let helper = () { "" }
  
  helper() == ""
}
```
