### ISSUE TITLE
Name Mint allready taken by another programming language

### ISSUE THREAD

**Issue by danielheinen** [mint-lang/mint#65]
http://www.abbmotion.com/products/mint/mintmt.asp

**Comment by r00ster91** [comment]
But on the website it's always exactly "MINT" in uppercase. But this mint is written like "Mint" so maybe it's okay.

**Comment by gdotdesign** [comment]
Thanks for poiting this out!

I agree with @r00ster91 it's not the same spelling and that language is not at all popular. I searched around when I choose the name `Mint` at it hasn't come up, also it's in a different context (not web development).

I think it's OK for now so I'm closing this issue, if Mint ever becomes popular we can reopen it to have a discussion.
