### ISSUE TITLE
Add ARM binaries to release page

### ISSUE THREAD

**Issue by fabasoad** [mint-lang/mint#689]
## Problem

Currently, `macos-latest` in [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) points to macOS 14 (M1) which is ARM. So, it makes `mint` impossible to be used in CI for all jobs that use `macos-latest` runners.

## Workaround

Use `macos-13` label instead of `macos-latest`.

## Solution

Add `mint-<version>-osx-arm` in addition to `mint-<version>-osx` and `mint-<version>-linux` to the [release page assets](https://github.com/mint-lang/mint/releases/tag/0.19.0). Would be also a ➕ to add `mint-<version>-linux-arm`.

**Comment by howlingblast** [comment]
Unfortunately building from source on macOS (Sequoia) doesn't work too (using `brew install --HEAD mint-lang`). This blocks trying out Mint, which is unfortunate for new users.

**Comment by gdotdesign** [comment]
There are two binaries for every release now, one for `macos-13` and `macos-latest` which is the `arm` one.
