### ISSUE TITLE
Binaries attached to v0.20.0-alpha.1 release prints wrong version

### ISSUE THREAD

**Issue by fabasoad** [mint-lang/mint#691]
### Steps to reproduce

1. Go to https://github.com/mint-lang/mint/releases/tag/0.20.0-alpha.1
2. Download and install binary (`*-linux`, `*-macos-*`)
3. Run `mint version`

### Actual behavior

```shell
Mint 0.19.0
```

### Expected behavior

```shell
Mint 0.20.0-alpha.1
```

**Comment by gdotdesign** [comment]
I forgot to update the version before creating the build, so it's still the correct code but with the old version label https://github.com/mint-lang/mint/blob/0.20.0-alpha.1/shard.yml#L2

Thanks for letting me know :pray:

**Comment by gdotdesign** [comment]
https://github.com/mint-lang/mint/commit/01199c9c1cc65dab6c2ce8ac3e1724350bc94f2b
