### ISSUE TITLE
Documentation Server doesn't set background color, can be illegible

### ISSUE THREAD

**Issue by AndydeCleyre** [mint-lang/mint#693]
The documentation served by `mint docs` does not specify the background color everywhere it does specify foreground colors. This means that if a user sets their browser's fallback colors as light-on-dark, these docs show up as dark-on-dark.

![image](https://github.com/user-attachments/assets/44c20920-7964-4a03-953d-6c290df1b186)

To reproduce:

- Open Firefox Preferences (`about:preferences`)
- Click on button "Manage Colors..."
- Change Text and Background colors to something light and dark, respectively (keep the default of *never* overriding sites' specified colors)
- `mint docs`

0.19.0

**Comment by gdotdesign** [comment]
The documentation server was rewritten in `0.20.0` and has a background color, so this is not an issue anymore.
