### ISSUE TITLE
Consider if..elsif..else

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#72]
Hi,

When I have multiple conditions to check - e.g. 
```
if (a > 1 && a <3){
  "A"
} else {
 if(a > 3 && a < 5){
  "B"
} else {
  "C"
}
}
```
It would be nicer to avoid the nesting if there was if..elsif..elsif..else where elsif is optional and can be as many as required.

maybe some kind of if could be applied to case statements to achieve something similar also.

**Comment by gdotdesign** [comment]
Good idea :+1: this will be a good addition.
