### ISSUE TITLE
Show version number on help menu of the command.

### ISSUE THREAD

**Issue by raguay** [mint-lang/mint#80]
The mint command doesn't show what version it is anywhere. It would be nice to show it in the help list so that I can make sure which version I am using.

**Comment by raguay** [comment]
I updated and there is nothing on the command line that says what version
of the mint compiler I am running.

**Comment by gdotdesign** [comment]
It's on master (daily binaries section) and will be available in the next release.

**Comment by gdotdesign** [comment]
It's available in 0.3.0
