### ISSUE TITLE
Consider line comment

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#81]
A line comment that is different from a block comment would be nice

1. just typing something like // at the start of the line is much more convenient than putting something at the front and the end 

2. Many editors have the concept of line and block comment - so my intellij plugin for example works a lot better with both.

The existing block comment is great `/* */`  

maybe a line comment could be `//`

**Comment by DanielSokil** [comment]
`#` could work also.

**Comment by wisn** [comment]
@gdotdesign I will trying to fix this issue. Could you give me a quick guide? I'm quite confused with the parsing flow. I'm new in Crystal tbh but I have experience in parsing

**Comment by kingsleyh** [comment]
@wisn maybe you could also help with the IntelliJ plugin

**Comment by Namek** [comment]
> @kingsleyh ah, I'm never using IntelliJ before so I will pass for now. I actually want to help but later when I have a good computer spec.

@wisn  How's your computer spec now? ^_^

**Comment by wisn** [comment]
> @wisn How's your computer spec now? ^_^

@Namek My current PC uses i3 processor with 12GB RAM. As for my office PC uses i7 processor with 16 GB RAM

**Comment by Namek** [comment]
@wisn I was indirectly asking if you are still willing to help with the task :) No pressure though

**Comment by wisn** [comment]
> @wisn I was indirectly asking if you are still willing to help with the task :) No pressure though

@Namek I'm actually aware. I will be back after I finished my undergraduate thesis. Like, maybe a month from now. If there is no one taking this by then issue, I will try to help.

**Comment by bbugh** [comment]
@wisn February can't come fast enough!

**Comment by wisn** [comment]
@bbugh lmaoo I actually forgot. sure I will relearn the codebase once again and then try to take this issue. I just joined Mint's Discord server. Feel free to mention me there since I was much more responsive on Discord :D

**Comment by wisn** [comment]
@kingsleyh is there any IntelliJ plugin for Mint that already exists? I would like to see it

**Comment by bbugh** [comment]
Added PR for the vscode extension to support line comments: https://github.com/mint-lang/mint-vscode/pull/23
