### ISSUE TITLE
Language/Library Features: Array.concat, RegExp.match

### ISSUE THREAD

**Issue by raguay** [mint-lang/mint#82]
Array module needs a concat method. The RegExp module needs a match method that returns a boolean with the matches? Or, just a boolean. Not sure which would be best.

**Comment by gdotdesign** [comment]
Also include methods form https://github.com/kingsleyh/array-extra/

**Comment by DanielSokil** [comment]
@gdotdesign 
https://github.com/kingsleyh/array-extra/ Has some great functions, but I think they can be more descriptive, for instance `foldr - Reduce a list from the right`.

`Array.prototype.reduceRight()` from JavaScript is more descriptive which leads to less metal proccessing.

**Comment by gdotdesign** [comment]
The following new functions have been added, and will be available in the next release:

- [x] Array.append
- [x] Array.concat
- [x] Array.reduceRight
- [x] Array.flatMap
- [x] Array.take
- [x] Array.drop
- [x] Array.groupsOf
- [x] Http.jsonBody
- [x] Window.confirm
- [x] Regexp.match (returns `Bool`)
- [x] Regexp.matches (retuns `Array(Regexp.Match)`)

Also added `Set` and `Map`.

**Comment by raguay** [comment]
You might want to check the Array.concat and Array.append to make sure they don't modify the passing arrays. I'm trying to use the Array.Extra.append in a project right now, but it keeps doubling the size of my array on each call due to the side effect of appending to the first array. I have a issue on that library for @gdotdesign to check into it.

**Comment by raguay** [comment]
Alright, the 0.0.3 version of the Array.Extras is now working without any side effects! Thanks @kingsleyh.

**Comment by gdotdesign** [comment]
It's released in https://github.com/mint-lang/mint-core/releases/tag/0.3.0
