### ISSUE TITLE
Consider supporting recursion

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/mint#97]
Recursion is a common choice for functional programmers. Consider trying to support it in the future.

**Comment by gdotdesign** [comment]
Recursion is now supported on functions:

```
fun fibonacci(num) {
  if (num <= 1) {
    1
  } else {
    return fibonacci(num - 1) + fibonacci(num - 2)
  }
}
```
 and components:
```
component Test {
  fun render : Html {
    <div>
      <Test/> 
    </div>
  } 
}
```

Every other type of recursion is still restricted, but these two should be the most use cases.

**Comment by lukepighetti** [comment]
I'm working on a Hacker News client using this API https://hn.algolia.com/api

The API uses record recursion for the Item record.

```mint
record Item {
  id : Number,
  createdAt : Time using "created_at",
  author : String,
  title : String,
  url : Url,
  text : Maybe(String),
  points : Number,
  parentId : Maybe(Number) using "parent_id",
  children : Array(Item)
}
```

What is the recommended way to handle this in Mint?

**Comment by gdotdesign** [comment]
I need to look into this but probably doable, provided the recursion takes place in an `Array` or `Map` so it won't go into an infinite loop when decoding.

**Comment by lukepighetti** [comment]
`Array`, `Map`, or `Maybe(type)` ?

**Comment by gdotdesign** [comment]
Yep these are the ones that could be supported (forgot about `Maybe` :))
